# ==============================================================
# File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
# Version: 2016.4
# Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
# 
# ==============================================================


vivado  -notrace -mode batch -source ipi_example.tcl -tclargs xc7z010clg400-2 ../xilinx_com_hls_calcDistancesHW_1_0.zip
