// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="calcDistancesHW,hls_ip_2016_4,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z010clg400-2,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.682000,HLS_SYN_LAT=475204,HLS_SYN_TPT=none,HLS_SYN_MEM=67,HLS_SYN_DSP=5,HLS_SYN_FF=1060,HLS_SYN_LUT=1652}" *)

module calcDistancesHW (
        ap_clk,
        ap_rst_n,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        data_hw_dout,
        data_hw_empty_n,
        data_hw_read,
        dists_hw_din,
        dists_hw_full_n,
        dists_hw_write
);


input   ap_clk;
input   ap_rst_n;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] data_hw_dout;
input   data_hw_empty_n;
output   data_hw_read;
output  [31:0] dists_hw_din;
input   dists_hw_full_n;
output   dists_hw_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg data_hw_read;
reg dists_hw_write;

reg    ap_rst_n_inv;
(* fsm_encoding = "none" *) reg   [30:0] ap_CS_fsm;
wire   [0:0] ap_CS_fsm_state1;
reg    data_hw_blk_n;
wire   [0:0] ap_CS_fsm_state3;
wire   [0:0] exitcond4_fu_288_p2;
reg    dists_hw_blk_n;
wire   [0:0] ap_CS_fsm_state31;
wire   [16:0] tmp_5_cast_fu_258_p1;
reg   [16:0] tmp_5_cast_reg_393;
wire   [0:0] ap_CS_fsm_state2;
wire   [10:0] i_2_fu_268_p2;
reg   [10:0] i_2_reg_401;
wire   [5:0] j_1_fu_294_p2;
reg    ap_block_state3;
wire   [31:0] i1_cast4_fu_300_p1;
reg   [31:0] i1_cast4_reg_414;
wire   [0:0] ap_CS_fsm_state4;
wire   [5:0] i_1_fu_311_p2;
reg   [5:0] i_1_reg_427;
wire   [31:0] i2_cast3_fu_317_p1;
reg   [31:0] i2_cast3_reg_432;
wire   [0:0] ap_CS_fsm_state6;
wire   [16:0] tmp_11_cast_fu_329_p1;
reg   [16:0] tmp_11_cast_reg_437;
wire   [10:0] i_4_fu_339_p2;
reg   [10:0] i_4_reg_445;
wire   [0:0] ap_CS_fsm_state7;
wire   [5:0] j_2_fu_370_p2;
reg   [5:0] j_2_reg_458;
wire   [0:0] exitcond1_fu_364_p2;
wire   [31:0] data_hw_tmp_q0;
reg   [31:0] data_hw_tmp_load_1_reg_468;
wire   [0:0] ap_CS_fsm_state8;
wire   [31:0] movie_tmp_q0;
reg   [31:0] movie_tmp_load_reg_473;
wire   [31:0] grp_fu_235_p2;
reg   [31:0] diff_reg_478;
wire   [0:0] ap_CS_fsm_state12;
wire   [31:0] grp_fu_240_p2;
reg   [31:0] tmp_9_reg_484;
wire   [0:0] ap_CS_fsm_state15;
wire   [0:0] ap_CS_fsm_state19;
wire   [31:0] grp_fu_244_p2;
reg   [31:0] tmp_6_reg_494;
wire   [0:0] ap_CS_fsm_state28;
wire   [10:0] i_3_fu_387_p2;
reg   [10:0] i_3_reg_502;
wire   [0:0] ap_CS_fsm_state30;
wire   [0:0] exitcond_fu_381_p2;
reg   [14:0] data_hw_tmp_address0;
reg    data_hw_tmp_ce0;
reg    data_hw_tmp_we0;
reg   [4:0] movie_tmp_address0;
reg    movie_tmp_ce0;
reg    movie_tmp_we0;
reg   [9:0] dists_hw_tmp_address0;
reg    dists_hw_tmp_ce0;
reg    dists_hw_tmp_we0;
wire   [31:0] dists_hw_tmp_q0;
reg   [10:0] i_reg_157;
reg   [5:0] j_reg_168;
wire   [0:0] exitcond5_fu_262_p2;
reg   [5:0] i1_reg_179;
wire   [0:0] ap_CS_fsm_state5;
reg   [10:0] i2_reg_190;
wire   [0:0] ap_CS_fsm_state29;
wire   [0:0] exitcond3_fu_305_p2;
reg   [31:0] sum_reg_201;
wire   [0:0] exitcond2_fu_333_p2;
reg   [5:0] j3_reg_213;
reg   [10:0] i4_reg_224;
wire   [31:0] tmp_8_cast_fu_283_p1;
wire   [31:0] tmp_12_cast_fu_359_p1;
wire   [31:0] j3_cast2_fu_345_p1;
wire   [31:0] i4_cast1_fu_376_p1;
reg   [31:0] grp_fu_235_p0;
reg   [31:0] grp_fu_235_p1;
wire   [0:0] ap_CS_fsm_state9;
wire   [0:0] ap_CS_fsm_state16;
wire   [0:0] ap_CS_fsm_state13;
wire   [15:0] tmp_4_fu_250_p3;
wire   [16:0] j_cast5_cast_fu_274_p1;
wire   [16:0] tmp_8_fu_278_p2;
wire   [15:0] tmp_s_fu_321_p3;
wire   [16:0] j3_cast2_cast_fu_350_p1;
wire   [16:0] tmp_3_fu_354_p2;
reg   [1:0] grp_fu_235_opcode;
reg   [30:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 31'd1;
end

calcDistancesHW_dbkb #(
    .DataWidth( 32 ),
    .AddressRange( 32768 ),
    .AddressWidth( 15 ))
data_hw_tmp_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(data_hw_tmp_address0),
    .ce0(data_hw_tmp_ce0),
    .we0(data_hw_tmp_we0),
    .d0(data_hw_dout),
    .q0(data_hw_tmp_q0)
);

calcDistancesHW_mcud #(
    .DataWidth( 32 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
movie_tmp_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(movie_tmp_address0),
    .ce0(movie_tmp_ce0),
    .we0(movie_tmp_we0),
    .d0(data_hw_tmp_q0),
    .q0(movie_tmp_q0)
);

calcDistancesHW_ddEe #(
    .DataWidth( 32 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
dists_hw_tmp_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(dists_hw_tmp_address0),
    .ce0(dists_hw_tmp_ce0),
    .we0(dists_hw_tmp_we0),
    .d0(tmp_6_reg_494),
    .q0(dists_hw_tmp_q0)
);

calcDistancesHW_feOg #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
calcDistancesHW_feOg_U1(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_235_p0),
    .din1(grp_fu_235_p1),
    .opcode(grp_fu_235_opcode),
    .ce(1'b1),
    .dout(grp_fu_235_p2)
);

calcDistancesHW_ffYi #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
calcDistancesHW_ffYi_U2(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(diff_reg_478),
    .din1(diff_reg_478),
    .ce(1'b1),
    .dout(grp_fu_240_p2)
);

calcDistancesHW_fg8j #(
    .ID( 1 ),
    .NUM_STAGE( 10 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
calcDistancesHW_fg8j_U3(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(32'd0),
    .din1(sum_reg_201),
    .ce(1'b1),
    .dout(grp_fu_244_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= 31'd1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == ap_CS_fsm_state2) & ~(1'd0 == exitcond5_fu_262_p2))) begin
        i1_reg_179 <= 6'd0;
    end else if ((1'd1 == ap_CS_fsm_state5)) begin
        i1_reg_179 <= i_1_reg_427;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == ap_CS_fsm_state4) & ~(1'd0 == exitcond3_fu_305_p2))) begin
        i2_reg_190 <= 11'd0;
    end else if ((1'd1 == ap_CS_fsm_state29)) begin
        i2_reg_190 <= i_4_reg_445;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == ap_CS_fsm_state6) & ~(1'd0 == exitcond2_fu_333_p2))) begin
        i4_reg_224 <= 11'd0;
    end else if (((1'd1 == ap_CS_fsm_state31) & ~(1'b0 == dists_hw_full_n))) begin
        i4_reg_224 <= i_3_reg_502;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == ap_CS_fsm_state3) & ~(1'b1 == ap_block_state3) & ~(exitcond4_fu_288_p2 == 1'd0))) begin
        i_reg_157 <= i_2_reg_401;
    end else if (((ap_CS_fsm_state1 == 1'd1) & ~(1'b0 == ap_start))) begin
        i_reg_157 <= 11'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'd1 == ap_CS_fsm_state19)) begin
        j3_reg_213 <= j_2_reg_458;
    end else if (((1'd1 == ap_CS_fsm_state6) & (1'd0 == exitcond2_fu_333_p2))) begin
        j3_reg_213 <= 6'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == ap_CS_fsm_state3) & (exitcond4_fu_288_p2 == 1'd0) & ~(1'b1 == ap_block_state3))) begin
        j_reg_168 <= j_1_fu_294_p2;
    end else if (((1'd1 == ap_CS_fsm_state2) & (1'd0 == exitcond5_fu_262_p2))) begin
        j_reg_168 <= 6'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'd1 == ap_CS_fsm_state19)) begin
        sum_reg_201 <= grp_fu_235_p2;
    end else if (((1'd1 == ap_CS_fsm_state6) & (1'd0 == exitcond2_fu_333_p2))) begin
        sum_reg_201 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'd1 == ap_CS_fsm_state8)) begin
        data_hw_tmp_load_1_reg_468 <= data_hw_tmp_q0;
        movie_tmp_load_reg_473 <= movie_tmp_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'd1 == ap_CS_fsm_state12)) begin
        diff_reg_478 <= grp_fu_235_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'd1 == ap_CS_fsm_state4)) begin
        i1_cast4_reg_414[5 : 0] <= i1_cast4_fu_300_p1[5 : 0];
        i_1_reg_427 <= i_1_fu_311_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'd1 == ap_CS_fsm_state6)) begin
        i2_cast3_reg_432[10 : 0] <= i2_cast3_fu_317_p1[10 : 0];
        i_4_reg_445 <= i_4_fu_339_p2;
        tmp_11_cast_reg_437[15 : 5] <= tmp_11_cast_fu_329_p1[15 : 5];
    end
end

always @ (posedge ap_clk) begin
    if ((1'd1 == ap_CS_fsm_state2)) begin
        i_2_reg_401 <= i_2_fu_268_p2;
        tmp_5_cast_reg_393[15 : 5] <= tmp_5_cast_fu_258_p1[15 : 5];
    end
end

always @ (posedge ap_clk) begin
    if ((1'd1 == ap_CS_fsm_state30)) begin
        i_3_reg_502 <= i_3_fu_387_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'd1 == ap_CS_fsm_state7)) begin
        j_2_reg_458 <= j_2_fu_370_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'd1 == ap_CS_fsm_state28)) begin
        tmp_6_reg_494 <= grp_fu_244_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'd1 == ap_CS_fsm_state15)) begin
        tmp_9_reg_484 <= grp_fu_240_p2;
    end
end

always @ (*) begin
    if (((1'd1 == ap_CS_fsm_state30) & ~(1'd0 == exitcond_fu_381_p2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (ap_CS_fsm_state1 == 1'd1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == ap_CS_fsm_state30) & ~(1'd0 == exitcond_fu_381_p2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == ap_CS_fsm_state3) & (exitcond4_fu_288_p2 == 1'd0))) begin
        data_hw_blk_n = data_hw_empty_n;
    end else begin
        data_hw_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'd1 == ap_CS_fsm_state3) & (exitcond4_fu_288_p2 == 1'd0) & ~(1'b1 == ap_block_state3))) begin
        data_hw_read = 1'b1;
    end else begin
        data_hw_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'd1 == ap_CS_fsm_state7)) begin
        data_hw_tmp_address0 = tmp_12_cast_fu_359_p1;
    end else if ((1'd1 == ap_CS_fsm_state4)) begin
        data_hw_tmp_address0 = i1_cast4_fu_300_p1;
    end else if ((1'd1 == ap_CS_fsm_state3)) begin
        data_hw_tmp_address0 = tmp_8_cast_fu_283_p1;
    end else begin
        data_hw_tmp_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'd1 == ap_CS_fsm_state3) & ~(1'b1 == ap_block_state3)) | (1'd1 == ap_CS_fsm_state4) | (1'd1 == ap_CS_fsm_state7))) begin
        data_hw_tmp_ce0 = 1'b1;
    end else begin
        data_hw_tmp_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == ap_CS_fsm_state3) & (exitcond4_fu_288_p2 == 1'd0) & ~(1'b1 == ap_block_state3))) begin
        data_hw_tmp_we0 = 1'b1;
    end else begin
        data_hw_tmp_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'd1 == ap_CS_fsm_state31)) begin
        dists_hw_blk_n = dists_hw_full_n;
    end else begin
        dists_hw_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'd1 == ap_CS_fsm_state30)) begin
        dists_hw_tmp_address0 = i4_cast1_fu_376_p1;
    end else if ((1'd1 == ap_CS_fsm_state29)) begin
        dists_hw_tmp_address0 = i2_cast3_reg_432;
    end else begin
        dists_hw_tmp_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'd1 == ap_CS_fsm_state30) | (1'd1 == ap_CS_fsm_state29))) begin
        dists_hw_tmp_ce0 = 1'b1;
    end else begin
        dists_hw_tmp_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'd1 == ap_CS_fsm_state29)) begin
        dists_hw_tmp_we0 = 1'b1;
    end else begin
        dists_hw_tmp_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == ap_CS_fsm_state31) & ~(1'b0 == dists_hw_full_n))) begin
        dists_hw_write = 1'b1;
    end else begin
        dists_hw_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'd1 == ap_CS_fsm_state9)) begin
        grp_fu_235_opcode = 2'd1;
    end else if ((1'd1 == ap_CS_fsm_state16)) begin
        grp_fu_235_opcode = 2'd0;
    end else begin
        grp_fu_235_opcode = 'bx;
    end
end

always @ (*) begin
    if ((1'd1 == ap_CS_fsm_state16)) begin
        grp_fu_235_p0 = sum_reg_201;
    end else if ((1'd1 == ap_CS_fsm_state9)) begin
        grp_fu_235_p0 = data_hw_tmp_load_1_reg_468;
    end else begin
        grp_fu_235_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'd1 == ap_CS_fsm_state16)) begin
        grp_fu_235_p1 = tmp_9_reg_484;
    end else if ((1'd1 == ap_CS_fsm_state9)) begin
        grp_fu_235_p1 = movie_tmp_load_reg_473;
    end else begin
        grp_fu_235_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'd1 == ap_CS_fsm_state7)) begin
        movie_tmp_address0 = j3_cast2_fu_345_p1;
    end else if ((1'd1 == ap_CS_fsm_state5)) begin
        movie_tmp_address0 = i1_cast4_reg_414;
    end else begin
        movie_tmp_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'd1 == ap_CS_fsm_state7) | (1'd1 == ap_CS_fsm_state5))) begin
        movie_tmp_ce0 = 1'b1;
    end else begin
        movie_tmp_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'd1 == ap_CS_fsm_state5)) begin
        movie_tmp_we0 = 1'b1;
    end else begin
        movie_tmp_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        31'd1 : begin
            if (~(1'b0 == ap_start)) begin
                ap_NS_fsm = 31'd2;
            end else begin
                ap_NS_fsm = 31'd1;
            end
        end
        31'd2 : begin
            if (~(1'd0 == exitcond5_fu_262_p2)) begin
                ap_NS_fsm = 31'd8;
            end else begin
                ap_NS_fsm = 31'd4;
            end
        end
        31'd4 : begin
            if ((~(1'b1 == ap_block_state3) & ~(exitcond4_fu_288_p2 == 1'd0))) begin
                ap_NS_fsm = 31'd2;
            end else if (((exitcond4_fu_288_p2 == 1'd0) & ~(1'b1 == ap_block_state3))) begin
                ap_NS_fsm = 31'd4;
            end else begin
                ap_NS_fsm = 31'd4;
            end
        end
        31'd8 : begin
            if (~(1'd0 == exitcond3_fu_305_p2)) begin
                ap_NS_fsm = 31'd32;
            end else begin
                ap_NS_fsm = 31'd16;
            end
        end
        31'd16 : begin
            ap_NS_fsm = 31'd8;
        end
        31'd32 : begin
            if (~(1'd0 == exitcond2_fu_333_p2)) begin
                ap_NS_fsm = 31'd536870912;
            end else begin
                ap_NS_fsm = 31'd64;
            end
        end
        31'd64 : begin
            if (~(1'd0 == exitcond1_fu_364_p2)) begin
                ap_NS_fsm = 31'd524288;
            end else begin
                ap_NS_fsm = 31'd128;
            end
        end
        31'd128 : begin
            ap_NS_fsm = 31'd256;
        end
        31'd256 : begin
            ap_NS_fsm = 31'd512;
        end
        31'd512 : begin
            ap_NS_fsm = 31'd1024;
        end
        31'd1024 : begin
            ap_NS_fsm = 31'd2048;
        end
        31'd2048 : begin
            ap_NS_fsm = 31'd4096;
        end
        31'd4096 : begin
            ap_NS_fsm = 31'd8192;
        end
        31'd8192 : begin
            ap_NS_fsm = 31'd16384;
        end
        31'd16384 : begin
            ap_NS_fsm = 31'd32768;
        end
        31'd32768 : begin
            ap_NS_fsm = 31'd65536;
        end
        31'd65536 : begin
            ap_NS_fsm = 31'd131072;
        end
        31'd131072 : begin
            ap_NS_fsm = 31'd262144;
        end
        31'd262144 : begin
            ap_NS_fsm = 31'd64;
        end
        31'd524288 : begin
            ap_NS_fsm = 31'd1048576;
        end
        31'd1048576 : begin
            ap_NS_fsm = 31'd2097152;
        end
        31'd2097152 : begin
            ap_NS_fsm = 31'd4194304;
        end
        31'd4194304 : begin
            ap_NS_fsm = 31'd8388608;
        end
        31'd8388608 : begin
            ap_NS_fsm = 31'd16777216;
        end
        31'd16777216 : begin
            ap_NS_fsm = 31'd33554432;
        end
        31'd33554432 : begin
            ap_NS_fsm = 31'd67108864;
        end
        31'd67108864 : begin
            ap_NS_fsm = 31'd134217728;
        end
        31'd134217728 : begin
            ap_NS_fsm = 31'd268435456;
        end
        31'd268435456 : begin
            ap_NS_fsm = 31'd32;
        end
        31'd536870912 : begin
            if (~(1'd0 == exitcond_fu_381_p2)) begin
                ap_NS_fsm = 31'd1;
            end else begin
                ap_NS_fsm = 31'd1073741824;
            end
        end
        31'd1073741824 : begin
            if (~(1'b0 == dists_hw_full_n)) begin
                ap_NS_fsm = 31'd536870912;
            end else begin
                ap_NS_fsm = 31'd1073741824;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state28 = ap_CS_fsm[32'd27];

assign ap_CS_fsm_state29 = ap_CS_fsm[32'd28];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state30 = ap_CS_fsm[32'd29];

assign ap_CS_fsm_state31 = ap_CS_fsm[32'd30];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state3 = ((exitcond4_fu_288_p2 == 1'd0) & (1'b0 == data_hw_empty_n));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign dists_hw_din = dists_hw_tmp_q0;

assign exitcond1_fu_364_p2 = ((j3_reg_213 == 6'd32) ? 1'b1 : 1'b0);

assign exitcond2_fu_333_p2 = ((i2_reg_190 == 11'd1024) ? 1'b1 : 1'b0);

assign exitcond3_fu_305_p2 = ((i1_reg_179 == 6'd32) ? 1'b1 : 1'b0);

assign exitcond4_fu_288_p2 = ((j_reg_168 == 6'd32) ? 1'b1 : 1'b0);

assign exitcond5_fu_262_p2 = ((i_reg_157 == 11'd1024) ? 1'b1 : 1'b0);

assign exitcond_fu_381_p2 = ((i4_reg_224 == 11'd1024) ? 1'b1 : 1'b0);

assign i1_cast4_fu_300_p1 = i1_reg_179;

assign i2_cast3_fu_317_p1 = i2_reg_190;

assign i4_cast1_fu_376_p1 = i4_reg_224;

assign i_1_fu_311_p2 = (i1_reg_179 + 6'd1);

assign i_2_fu_268_p2 = (i_reg_157 + 11'd1);

assign i_3_fu_387_p2 = (i4_reg_224 + 11'd1);

assign i_4_fu_339_p2 = (i2_reg_190 + 11'd1);

assign j3_cast2_cast_fu_350_p1 = j3_reg_213;

assign j3_cast2_fu_345_p1 = j3_reg_213;

assign j_1_fu_294_p2 = (j_reg_168 + 6'd1);

assign j_2_fu_370_p2 = (j3_reg_213 + 6'd1);

assign j_cast5_cast_fu_274_p1 = j_reg_168;

assign tmp_11_cast_fu_329_p1 = tmp_s_fu_321_p3;

assign tmp_12_cast_fu_359_p1 = tmp_3_fu_354_p2;

assign tmp_3_fu_354_p2 = (tmp_11_cast_reg_437 + j3_cast2_cast_fu_350_p1);

assign tmp_4_fu_250_p3 = {{i_reg_157}, {5'd0}};

assign tmp_5_cast_fu_258_p1 = tmp_4_fu_250_p3;

assign tmp_8_cast_fu_283_p1 = tmp_8_fu_278_p2;

assign tmp_8_fu_278_p2 = (tmp_5_cast_reg_393 + j_cast5_cast_fu_274_p1);

assign tmp_s_fu_321_p3 = {{i2_reg_190}, {5'd0}};

always @ (posedge ap_clk) begin
    tmp_5_cast_reg_393[4:0] <= 5'b00000;
    tmp_5_cast_reg_393[16] <= 1'b0;
    i1_cast4_reg_414[31:6] <= 26'b00000000000000000000000000;
    i2_cast3_reg_432[31:11] <= 21'b000000000000000000000;
    tmp_11_cast_reg_437[4:0] <= 5'b00000;
    tmp_11_cast_reg_437[16] <= 1'b0;
end

endmodule //calcDistancesHW
