-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2016.4
-- Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity calcDistancesHW is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    data_hw_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    data_hw_empty_n : IN STD_LOGIC;
    data_hw_read : OUT STD_LOGIC;
    dists_hw_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    dists_hw_full_n : IN STD_LOGIC;
    dists_hw_write : OUT STD_LOGIC );
end;


architecture behav of calcDistancesHW is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "calcDistancesHW,hls_ip_2016_4,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z010clg400-2,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.682000,HLS_SYN_LAT=475204,HLS_SYN_TPT=none,HLS_SYN_MEM=67,HLS_SYN_DSP=5,HLS_SYN_FF=1060,HLS_SYN_LUT=1652}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000001000000000000000";
    constant ap_ST_fsm_state17 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000010000000000000000";
    constant ap_ST_fsm_state18 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000100000000000000000";
    constant ap_ST_fsm_state19 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000001000000000000000000";
    constant ap_ST_fsm_state20 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000010000000000000000000";
    constant ap_ST_fsm_state21 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000100000000000000000000";
    constant ap_ST_fsm_state22 : STD_LOGIC_VECTOR (30 downto 0) := "0000000001000000000000000000000";
    constant ap_ST_fsm_state23 : STD_LOGIC_VECTOR (30 downto 0) := "0000000010000000000000000000000";
    constant ap_ST_fsm_state24 : STD_LOGIC_VECTOR (30 downto 0) := "0000000100000000000000000000000";
    constant ap_ST_fsm_state25 : STD_LOGIC_VECTOR (30 downto 0) := "0000001000000000000000000000000";
    constant ap_ST_fsm_state26 : STD_LOGIC_VECTOR (30 downto 0) := "0000010000000000000000000000000";
    constant ap_ST_fsm_state27 : STD_LOGIC_VECTOR (30 downto 0) := "0000100000000000000000000000000";
    constant ap_ST_fsm_state28 : STD_LOGIC_VECTOR (30 downto 0) := "0001000000000000000000000000000";
    constant ap_ST_fsm_state29 : STD_LOGIC_VECTOR (30 downto 0) := "0010000000000000000000000000000";
    constant ap_ST_fsm_state30 : STD_LOGIC_VECTOR (30 downto 0) := "0100000000000000000000000000000";
    constant ap_ST_fsm_state31 : STD_LOGIC_VECTOR (30 downto 0) := "1000000000000000000000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_1B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011011";
    constant ap_const_lv32_1D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011101";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_1C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011100";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv11_400 : STD_LOGIC_VECTOR (10 downto 0) := "10000000000";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv6_20 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal data_hw_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state3 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal exitcond4_fu_288_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal dists_hw_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state31 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_state31 : signal is "none";
    signal tmp_5_cast_fu_258_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_5_cast_reg_393 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal i_2_fu_268_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal i_2_reg_401 : STD_LOGIC_VECTOR (10 downto 0);
    signal j_1_fu_294_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_block_state3 : BOOLEAN;
    signal i1_cast4_fu_300_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal i1_cast4_reg_414 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal i_1_fu_311_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal i_1_reg_427 : STD_LOGIC_VECTOR (5 downto 0);
    signal i2_cast3_fu_317_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal i2_cast3_reg_432 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal tmp_11_cast_fu_329_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_11_cast_reg_437 : STD_LOGIC_VECTOR (16 downto 0);
    signal i_4_fu_339_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal i_4_reg_445 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal j_2_fu_370_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal j_2_reg_458 : STD_LOGIC_VECTOR (5 downto 0);
    signal exitcond1_fu_364_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal data_hw_tmp_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal data_hw_tmp_load_1_reg_468 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal movie_tmp_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal movie_tmp_load_reg_473 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_235_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal diff_reg_478 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state12 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal grp_fu_240_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_9_reg_484 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state15 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_state15 : signal is "none";
    signal ap_CS_fsm_state19 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_state19 : signal is "none";
    signal grp_fu_244_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_6_reg_494 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state28 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_state28 : signal is "none";
    signal i_3_fu_387_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal i_3_reg_502 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_CS_fsm_state30 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_state30 : signal is "none";
    signal exitcond_fu_381_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal data_hw_tmp_address0 : STD_LOGIC_VECTOR (14 downto 0);
    signal data_hw_tmp_ce0 : STD_LOGIC;
    signal data_hw_tmp_we0 : STD_LOGIC;
    signal movie_tmp_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal movie_tmp_ce0 : STD_LOGIC;
    signal movie_tmp_we0 : STD_LOGIC;
    signal dists_hw_tmp_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal dists_hw_tmp_ce0 : STD_LOGIC;
    signal dists_hw_tmp_we0 : STD_LOGIC;
    signal dists_hw_tmp_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal i_reg_157 : STD_LOGIC_VECTOR (10 downto 0);
    signal j_reg_168 : STD_LOGIC_VECTOR (5 downto 0);
    signal exitcond5_fu_262_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal i1_reg_179 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal i2_reg_190 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_CS_fsm_state29 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_state29 : signal is "none";
    signal exitcond3_fu_305_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sum_reg_201 : STD_LOGIC_VECTOR (31 downto 0);
    signal exitcond2_fu_333_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal j3_reg_213 : STD_LOGIC_VECTOR (5 downto 0);
    signal i4_reg_224 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_8_cast_fu_283_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_12_cast_fu_359_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal j3_cast2_fu_345_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal i4_cast1_fu_376_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_235_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_235_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal ap_CS_fsm_state16 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_state16 : signal is "none";
    signal ap_CS_fsm_state13 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal tmp_4_fu_250_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal j_cast5_cast_fu_274_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_8_fu_278_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_s_fu_321_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal j3_cast2_cast_fu_350_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_3_fu_354_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_235_opcode : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (30 downto 0);

    component calcDistancesHW_feOg IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        opcode : IN STD_LOGIC_VECTOR (1 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component calcDistancesHW_ffYi IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component calcDistancesHW_fg8j IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component calcDistancesHW_dbkb IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (14 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component calcDistancesHW_mcud IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component calcDistancesHW_ddEe IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    data_hw_tmp_U : component calcDistancesHW_dbkb
    generic map (
        DataWidth => 32,
        AddressRange => 32768,
        AddressWidth => 15)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => data_hw_tmp_address0,
        ce0 => data_hw_tmp_ce0,
        we0 => data_hw_tmp_we0,
        d0 => data_hw_dout,
        q0 => data_hw_tmp_q0);

    movie_tmp_U : component calcDistancesHW_mcud
    generic map (
        DataWidth => 32,
        AddressRange => 32,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => movie_tmp_address0,
        ce0 => movie_tmp_ce0,
        we0 => movie_tmp_we0,
        d0 => data_hw_tmp_q0,
        q0 => movie_tmp_q0);

    dists_hw_tmp_U : component calcDistancesHW_ddEe
    generic map (
        DataWidth => 32,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => dists_hw_tmp_address0,
        ce0 => dists_hw_tmp_ce0,
        we0 => dists_hw_tmp_we0,
        d0 => tmp_6_reg_494,
        q0 => dists_hw_tmp_q0);

    calcDistancesHW_feOg_U1 : component calcDistancesHW_feOg
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => grp_fu_235_p0,
        din1 => grp_fu_235_p1,
        opcode => grp_fu_235_opcode,
        ce => ap_const_logic_1,
        dout => grp_fu_235_p2);

    calcDistancesHW_ffYi_U2 : component calcDistancesHW_ffYi
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => diff_reg_478,
        din1 => diff_reg_478,
        ce => ap_const_logic_1,
        dout => grp_fu_240_p2);

    calcDistancesHW_fg8j_U3 : component calcDistancesHW_fg8j
    generic map (
        ID => 1,
        NUM_STAGE => 10,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => ap_const_lv32_0,
        din1 => sum_reg_201,
        ce => ap_const_logic_1,
        dout => grp_fu_244_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    i1_reg_179_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = ap_CS_fsm_state2) and not((ap_const_lv1_0 = exitcond5_fu_262_p2)))) then 
                i1_reg_179 <= ap_const_lv6_0;
            elsif ((ap_const_lv1_1 = ap_CS_fsm_state5)) then 
                i1_reg_179 <= i_1_reg_427;
            end if; 
        end if;
    end process;

    i2_reg_190_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = ap_CS_fsm_state4) and not((ap_const_lv1_0 = exitcond3_fu_305_p2)))) then 
                i2_reg_190 <= ap_const_lv11_0;
            elsif ((ap_const_lv1_1 = ap_CS_fsm_state29)) then 
                i2_reg_190 <= i_4_reg_445;
            end if; 
        end if;
    end process;

    i4_reg_224_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = ap_CS_fsm_state6) and not((ap_const_lv1_0 = exitcond2_fu_333_p2)))) then 
                i4_reg_224 <= ap_const_lv11_0;
            elsif (((ap_const_lv1_1 = ap_CS_fsm_state31) and not((ap_const_logic_0 = dists_hw_full_n)))) then 
                i4_reg_224 <= i_3_reg_502;
            end if; 
        end if;
    end process;

    i_reg_157_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = ap_CS_fsm_state3) and not((ap_const_boolean_1 = ap_block_state3)) and not((exitcond4_fu_288_p2 = ap_const_lv1_0)))) then 
                i_reg_157 <= i_2_reg_401;
            elsif (((ap_CS_fsm_state1 = ap_const_lv1_1) and not((ap_const_logic_0 = ap_start)))) then 
                i_reg_157 <= ap_const_lv11_0;
            end if; 
        end if;
    end process;

    j3_reg_213_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_lv1_1 = ap_CS_fsm_state19)) then 
                j3_reg_213 <= j_2_reg_458;
            elsif (((ap_const_lv1_1 = ap_CS_fsm_state6) and (ap_const_lv1_0 = exitcond2_fu_333_p2))) then 
                j3_reg_213 <= ap_const_lv6_0;
            end if; 
        end if;
    end process;

    j_reg_168_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = ap_CS_fsm_state3) and (exitcond4_fu_288_p2 = ap_const_lv1_0) and not((ap_const_boolean_1 = ap_block_state3)))) then 
                j_reg_168 <= j_1_fu_294_p2;
            elsif (((ap_const_lv1_1 = ap_CS_fsm_state2) and (ap_const_lv1_0 = exitcond5_fu_262_p2))) then 
                j_reg_168 <= ap_const_lv6_0;
            end if; 
        end if;
    end process;

    sum_reg_201_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_lv1_1 = ap_CS_fsm_state19)) then 
                sum_reg_201 <= grp_fu_235_p2;
            elsif (((ap_const_lv1_1 = ap_CS_fsm_state6) and (ap_const_lv1_0 = exitcond2_fu_333_p2))) then 
                sum_reg_201 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_lv1_1 = ap_CS_fsm_state8)) then
                data_hw_tmp_load_1_reg_468 <= data_hw_tmp_q0;
                movie_tmp_load_reg_473 <= movie_tmp_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_lv1_1 = ap_CS_fsm_state12)) then
                diff_reg_478 <= grp_fu_235_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_lv1_1 = ap_CS_fsm_state4)) then
                    i1_cast4_reg_414(5 downto 0) <= i1_cast4_fu_300_p1(5 downto 0);
                i_1_reg_427 <= i_1_fu_311_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_lv1_1 = ap_CS_fsm_state6)) then
                    i2_cast3_reg_432(10 downto 0) <= i2_cast3_fu_317_p1(10 downto 0);
                i_4_reg_445 <= i_4_fu_339_p2;
                    tmp_11_cast_reg_437(15 downto 5) <= tmp_11_cast_fu_329_p1(15 downto 5);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_lv1_1 = ap_CS_fsm_state2)) then
                i_2_reg_401 <= i_2_fu_268_p2;
                    tmp_5_cast_reg_393(15 downto 5) <= tmp_5_cast_fu_258_p1(15 downto 5);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_lv1_1 = ap_CS_fsm_state30)) then
                i_3_reg_502 <= i_3_fu_387_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_lv1_1 = ap_CS_fsm_state7)) then
                j_2_reg_458 <= j_2_fu_370_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_lv1_1 = ap_CS_fsm_state28)) then
                tmp_6_reg_494 <= grp_fu_244_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_lv1_1 = ap_CS_fsm_state15)) then
                tmp_9_reg_484 <= grp_fu_240_p2;
            end if;
        end if;
    end process;
    tmp_5_cast_reg_393(4 downto 0) <= "00000";
    tmp_5_cast_reg_393(16) <= '0';
    i1_cast4_reg_414(31 downto 6) <= "00000000000000000000000000";
    i2_cast3_reg_432(31 downto 11) <= "000000000000000000000";
    tmp_11_cast_reg_437(4 downto 0) <= "00000";
    tmp_11_cast_reg_437(16) <= '0';

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, dists_hw_full_n, exitcond4_fu_288_p2, ap_block_state3, exitcond1_fu_364_p2, exitcond_fu_381_p2, exitcond5_fu_262_p2, exitcond3_fu_305_p2, exitcond2_fu_333_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (not((ap_const_logic_0 = ap_start))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (not((ap_const_lv1_0 = exitcond5_fu_262_p2))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if ((not((ap_const_boolean_1 = ap_block_state3)) and not((exitcond4_fu_288_p2 = ap_const_lv1_0)))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                elsif (((exitcond4_fu_288_p2 = ap_const_lv1_0) and not((ap_const_boolean_1 = ap_block_state3)))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                if (not((ap_const_lv1_0 = exitcond3_fu_305_p2))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state6 => 
                if (not((ap_const_lv1_0 = exitcond2_fu_333_p2))) then
                    ap_NS_fsm <= ap_ST_fsm_state30;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_state7 => 
                if (not((ap_const_lv1_0 = exitcond1_fu_364_p2))) then
                    ap_NS_fsm <= ap_ST_fsm_state20;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state15;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state16;
            when ap_ST_fsm_state16 => 
                ap_NS_fsm <= ap_ST_fsm_state17;
            when ap_ST_fsm_state17 => 
                ap_NS_fsm <= ap_ST_fsm_state18;
            when ap_ST_fsm_state18 => 
                ap_NS_fsm <= ap_ST_fsm_state19;
            when ap_ST_fsm_state19 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state20 => 
                ap_NS_fsm <= ap_ST_fsm_state21;
            when ap_ST_fsm_state21 => 
                ap_NS_fsm <= ap_ST_fsm_state22;
            when ap_ST_fsm_state22 => 
                ap_NS_fsm <= ap_ST_fsm_state23;
            when ap_ST_fsm_state23 => 
                ap_NS_fsm <= ap_ST_fsm_state24;
            when ap_ST_fsm_state24 => 
                ap_NS_fsm <= ap_ST_fsm_state25;
            when ap_ST_fsm_state25 => 
                ap_NS_fsm <= ap_ST_fsm_state26;
            when ap_ST_fsm_state26 => 
                ap_NS_fsm <= ap_ST_fsm_state27;
            when ap_ST_fsm_state27 => 
                ap_NS_fsm <= ap_ST_fsm_state28;
            when ap_ST_fsm_state28 => 
                ap_NS_fsm <= ap_ST_fsm_state29;
            when ap_ST_fsm_state29 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state30 => 
                if (not((ap_const_lv1_0 = exitcond_fu_381_p2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state31;
                end if;
            when ap_ST_fsm_state31 => 
                if (not((ap_const_logic_0 = dists_hw_full_n))) then
                    ap_NS_fsm <= ap_ST_fsm_state30;
                else
                    ap_NS_fsm <= ap_ST_fsm_state31;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0 downto 0);
    ap_CS_fsm_state12 <= ap_CS_fsm(11 downto 11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12 downto 12);
    ap_CS_fsm_state15 <= ap_CS_fsm(14 downto 14);
    ap_CS_fsm_state16 <= ap_CS_fsm(15 downto 15);
    ap_CS_fsm_state19 <= ap_CS_fsm(18 downto 18);
    ap_CS_fsm_state2 <= ap_CS_fsm(1 downto 1);
    ap_CS_fsm_state28 <= ap_CS_fsm(27 downto 27);
    ap_CS_fsm_state29 <= ap_CS_fsm(28 downto 28);
    ap_CS_fsm_state3 <= ap_CS_fsm(2 downto 2);
    ap_CS_fsm_state30 <= ap_CS_fsm(29 downto 29);
    ap_CS_fsm_state31 <= ap_CS_fsm(30 downto 30);
    ap_CS_fsm_state4 <= ap_CS_fsm(3 downto 3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4 downto 4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5 downto 5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6 downto 6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7 downto 7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8 downto 8);

    ap_block_state3_assign_proc : process(data_hw_empty_n, exitcond4_fu_288_p2)
    begin
                ap_block_state3 <= ((exitcond4_fu_288_p2 = ap_const_lv1_0) and (ap_const_logic_0 = data_hw_empty_n));
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state30, exitcond_fu_381_p2)
    begin
        if (((ap_const_lv1_1 = ap_CS_fsm_state30) and not((ap_const_lv1_0 = exitcond_fu_381_p2)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_0 = ap_start) and (ap_CS_fsm_state1 = ap_const_lv1_1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state30, exitcond_fu_381_p2)
    begin
        if (((ap_const_lv1_1 = ap_CS_fsm_state30) and not((ap_const_lv1_0 = exitcond_fu_381_p2)))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;


    data_hw_blk_n_assign_proc : process(data_hw_empty_n, ap_CS_fsm_state3, exitcond4_fu_288_p2)
    begin
        if (((ap_const_lv1_1 = ap_CS_fsm_state3) and (exitcond4_fu_288_p2 = ap_const_lv1_0))) then 
            data_hw_blk_n <= data_hw_empty_n;
        else 
            data_hw_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_hw_read_assign_proc : process(ap_CS_fsm_state3, exitcond4_fu_288_p2, ap_block_state3)
    begin
        if (((ap_const_lv1_1 = ap_CS_fsm_state3) and (exitcond4_fu_288_p2 = ap_const_lv1_0) and not((ap_const_boolean_1 = ap_block_state3)))) then 
            data_hw_read <= ap_const_logic_1;
        else 
            data_hw_read <= ap_const_logic_0;
        end if; 
    end process;


    data_hw_tmp_address0_assign_proc : process(ap_CS_fsm_state3, i1_cast4_fu_300_p1, ap_CS_fsm_state4, ap_CS_fsm_state7, tmp_8_cast_fu_283_p1, tmp_12_cast_fu_359_p1)
    begin
        if ((ap_const_lv1_1 = ap_CS_fsm_state7)) then 
            data_hw_tmp_address0 <= tmp_12_cast_fu_359_p1(15 - 1 downto 0);
        elsif ((ap_const_lv1_1 = ap_CS_fsm_state4)) then 
            data_hw_tmp_address0 <= i1_cast4_fu_300_p1(15 - 1 downto 0);
        elsif ((ap_const_lv1_1 = ap_CS_fsm_state3)) then 
            data_hw_tmp_address0 <= tmp_8_cast_fu_283_p1(15 - 1 downto 0);
        else 
            data_hw_tmp_address0 <= "XXXXXXXXXXXXXXX";
        end if; 
    end process;


    data_hw_tmp_ce0_assign_proc : process(ap_CS_fsm_state3, ap_block_state3, ap_CS_fsm_state4, ap_CS_fsm_state7)
    begin
        if ((((ap_const_lv1_1 = ap_CS_fsm_state3) and not((ap_const_boolean_1 = ap_block_state3))) or (ap_const_lv1_1 = ap_CS_fsm_state4) or (ap_const_lv1_1 = ap_CS_fsm_state7))) then 
            data_hw_tmp_ce0 <= ap_const_logic_1;
        else 
            data_hw_tmp_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    data_hw_tmp_we0_assign_proc : process(ap_CS_fsm_state3, exitcond4_fu_288_p2, ap_block_state3)
    begin
        if (((ap_const_lv1_1 = ap_CS_fsm_state3) and (exitcond4_fu_288_p2 = ap_const_lv1_0) and not((ap_const_boolean_1 = ap_block_state3)))) then 
            data_hw_tmp_we0 <= ap_const_logic_1;
        else 
            data_hw_tmp_we0 <= ap_const_logic_0;
        end if; 
    end process;


    dists_hw_blk_n_assign_proc : process(dists_hw_full_n, ap_CS_fsm_state31)
    begin
        if ((ap_const_lv1_1 = ap_CS_fsm_state31)) then 
            dists_hw_blk_n <= dists_hw_full_n;
        else 
            dists_hw_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    dists_hw_din <= dists_hw_tmp_q0;

    dists_hw_tmp_address0_assign_proc : process(i2_cast3_reg_432, ap_CS_fsm_state30, ap_CS_fsm_state29, i4_cast1_fu_376_p1)
    begin
        if ((ap_const_lv1_1 = ap_CS_fsm_state30)) then 
            dists_hw_tmp_address0 <= i4_cast1_fu_376_p1(10 - 1 downto 0);
        elsif ((ap_const_lv1_1 = ap_CS_fsm_state29)) then 
            dists_hw_tmp_address0 <= i2_cast3_reg_432(10 - 1 downto 0);
        else 
            dists_hw_tmp_address0 <= "XXXXXXXXXX";
        end if; 
    end process;


    dists_hw_tmp_ce0_assign_proc : process(ap_CS_fsm_state30, ap_CS_fsm_state29)
    begin
        if (((ap_const_lv1_1 = ap_CS_fsm_state30) or (ap_const_lv1_1 = ap_CS_fsm_state29))) then 
            dists_hw_tmp_ce0 <= ap_const_logic_1;
        else 
            dists_hw_tmp_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    dists_hw_tmp_we0_assign_proc : process(ap_CS_fsm_state29)
    begin
        if ((ap_const_lv1_1 = ap_CS_fsm_state29)) then 
            dists_hw_tmp_we0 <= ap_const_logic_1;
        else 
            dists_hw_tmp_we0 <= ap_const_logic_0;
        end if; 
    end process;


    dists_hw_write_assign_proc : process(dists_hw_full_n, ap_CS_fsm_state31)
    begin
        if (((ap_const_lv1_1 = ap_CS_fsm_state31) and not((ap_const_logic_0 = dists_hw_full_n)))) then 
            dists_hw_write <= ap_const_logic_1;
        else 
            dists_hw_write <= ap_const_logic_0;
        end if; 
    end process;

    exitcond1_fu_364_p2 <= "1" when (j3_reg_213 = ap_const_lv6_20) else "0";
    exitcond2_fu_333_p2 <= "1" when (i2_reg_190 = ap_const_lv11_400) else "0";
    exitcond3_fu_305_p2 <= "1" when (i1_reg_179 = ap_const_lv6_20) else "0";
    exitcond4_fu_288_p2 <= "1" when (j_reg_168 = ap_const_lv6_20) else "0";
    exitcond5_fu_262_p2 <= "1" when (i_reg_157 = ap_const_lv11_400) else "0";
    exitcond_fu_381_p2 <= "1" when (i4_reg_224 = ap_const_lv11_400) else "0";

    grp_fu_235_opcode_assign_proc : process(ap_CS_fsm_state9, ap_CS_fsm_state16)
    begin
        if ((ap_const_lv1_1 = ap_CS_fsm_state9)) then 
            grp_fu_235_opcode <= ap_const_lv2_1;
        elsif ((ap_const_lv1_1 = ap_CS_fsm_state16)) then 
            grp_fu_235_opcode <= ap_const_lv2_0;
        else 
            grp_fu_235_opcode <= "XX";
        end if; 
    end process;


    grp_fu_235_p0_assign_proc : process(data_hw_tmp_load_1_reg_468, sum_reg_201, ap_CS_fsm_state9, ap_CS_fsm_state16)
    begin
        if ((ap_const_lv1_1 = ap_CS_fsm_state16)) then 
            grp_fu_235_p0 <= sum_reg_201;
        elsif ((ap_const_lv1_1 = ap_CS_fsm_state9)) then 
            grp_fu_235_p0 <= data_hw_tmp_load_1_reg_468;
        else 
            grp_fu_235_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_235_p1_assign_proc : process(movie_tmp_load_reg_473, tmp_9_reg_484, ap_CS_fsm_state9, ap_CS_fsm_state16)
    begin
        if ((ap_const_lv1_1 = ap_CS_fsm_state16)) then 
            grp_fu_235_p1 <= tmp_9_reg_484;
        elsif ((ap_const_lv1_1 = ap_CS_fsm_state9)) then 
            grp_fu_235_p1 <= movie_tmp_load_reg_473;
        else 
            grp_fu_235_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    i1_cast4_fu_300_p1 <= std_logic_vector(resize(unsigned(i1_reg_179),32));
    i2_cast3_fu_317_p1 <= std_logic_vector(resize(unsigned(i2_reg_190),32));
    i4_cast1_fu_376_p1 <= std_logic_vector(resize(unsigned(i4_reg_224),32));
    i_1_fu_311_p2 <= std_logic_vector(unsigned(i1_reg_179) + unsigned(ap_const_lv6_1));
    i_2_fu_268_p2 <= std_logic_vector(unsigned(i_reg_157) + unsigned(ap_const_lv11_1));
    i_3_fu_387_p2 <= std_logic_vector(unsigned(i4_reg_224) + unsigned(ap_const_lv11_1));
    i_4_fu_339_p2 <= std_logic_vector(unsigned(i2_reg_190) + unsigned(ap_const_lv11_1));
    j3_cast2_cast_fu_350_p1 <= std_logic_vector(resize(unsigned(j3_reg_213),17));
    j3_cast2_fu_345_p1 <= std_logic_vector(resize(unsigned(j3_reg_213),32));
    j_1_fu_294_p2 <= std_logic_vector(unsigned(j_reg_168) + unsigned(ap_const_lv6_1));
    j_2_fu_370_p2 <= std_logic_vector(unsigned(j3_reg_213) + unsigned(ap_const_lv6_1));
    j_cast5_cast_fu_274_p1 <= std_logic_vector(resize(unsigned(j_reg_168),17));

    movie_tmp_address0_assign_proc : process(i1_cast4_reg_414, ap_CS_fsm_state7, ap_CS_fsm_state5, j3_cast2_fu_345_p1)
    begin
        if ((ap_const_lv1_1 = ap_CS_fsm_state7)) then 
            movie_tmp_address0 <= j3_cast2_fu_345_p1(5 - 1 downto 0);
        elsif ((ap_const_lv1_1 = ap_CS_fsm_state5)) then 
            movie_tmp_address0 <= i1_cast4_reg_414(5 - 1 downto 0);
        else 
            movie_tmp_address0 <= "XXXXX";
        end if; 
    end process;


    movie_tmp_ce0_assign_proc : process(ap_CS_fsm_state7, ap_CS_fsm_state5)
    begin
        if (((ap_const_lv1_1 = ap_CS_fsm_state7) or (ap_const_lv1_1 = ap_CS_fsm_state5))) then 
            movie_tmp_ce0 <= ap_const_logic_1;
        else 
            movie_tmp_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    movie_tmp_we0_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_lv1_1 = ap_CS_fsm_state5)) then 
            movie_tmp_we0 <= ap_const_logic_1;
        else 
            movie_tmp_we0 <= ap_const_logic_0;
        end if; 
    end process;

    tmp_11_cast_fu_329_p1 <= std_logic_vector(resize(unsigned(tmp_s_fu_321_p3),17));
    tmp_12_cast_fu_359_p1 <= std_logic_vector(resize(unsigned(tmp_3_fu_354_p2),32));
    tmp_3_fu_354_p2 <= std_logic_vector(unsigned(tmp_11_cast_reg_437) + unsigned(j3_cast2_cast_fu_350_p1));
    tmp_4_fu_250_p3 <= (i_reg_157 & ap_const_lv5_0);
    tmp_5_cast_fu_258_p1 <= std_logic_vector(resize(unsigned(tmp_4_fu_250_p3),17));
    tmp_8_cast_fu_283_p1 <= std_logic_vector(resize(unsigned(tmp_8_fu_278_p2),32));
    tmp_8_fu_278_p2 <= std_logic_vector(unsigned(tmp_5_cast_reg_393) + unsigned(j_cast5_cast_fu_274_p1));
    tmp_s_fu_321_p3 <= (i2_reg_190 & ap_const_lv5_0);
end behav;
