// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "calcDistancesHW.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic calcDistancesHW::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic calcDistancesHW::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<31> calcDistancesHW::ap_ST_fsm_state1 = "1";
const sc_lv<31> calcDistancesHW::ap_ST_fsm_state2 = "10";
const sc_lv<31> calcDistancesHW::ap_ST_fsm_state3 = "100";
const sc_lv<31> calcDistancesHW::ap_ST_fsm_state4 = "1000";
const sc_lv<31> calcDistancesHW::ap_ST_fsm_state5 = "10000";
const sc_lv<31> calcDistancesHW::ap_ST_fsm_state6 = "100000";
const sc_lv<31> calcDistancesHW::ap_ST_fsm_state7 = "1000000";
const sc_lv<31> calcDistancesHW::ap_ST_fsm_state8 = "10000000";
const sc_lv<31> calcDistancesHW::ap_ST_fsm_state9 = "100000000";
const sc_lv<31> calcDistancesHW::ap_ST_fsm_state10 = "1000000000";
const sc_lv<31> calcDistancesHW::ap_ST_fsm_state11 = "10000000000";
const sc_lv<31> calcDistancesHW::ap_ST_fsm_state12 = "100000000000";
const sc_lv<31> calcDistancesHW::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<31> calcDistancesHW::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<31> calcDistancesHW::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<31> calcDistancesHW::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<31> calcDistancesHW::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<31> calcDistancesHW::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<31> calcDistancesHW::ap_ST_fsm_state19 = "1000000000000000000";
const sc_lv<31> calcDistancesHW::ap_ST_fsm_state20 = "10000000000000000000";
const sc_lv<31> calcDistancesHW::ap_ST_fsm_state21 = "100000000000000000000";
const sc_lv<31> calcDistancesHW::ap_ST_fsm_state22 = "1000000000000000000000";
const sc_lv<31> calcDistancesHW::ap_ST_fsm_state23 = "10000000000000000000000";
const sc_lv<31> calcDistancesHW::ap_ST_fsm_state24 = "100000000000000000000000";
const sc_lv<31> calcDistancesHW::ap_ST_fsm_state25 = "1000000000000000000000000";
const sc_lv<31> calcDistancesHW::ap_ST_fsm_state26 = "10000000000000000000000000";
const sc_lv<31> calcDistancesHW::ap_ST_fsm_state27 = "100000000000000000000000000";
const sc_lv<31> calcDistancesHW::ap_ST_fsm_state28 = "1000000000000000000000000000";
const sc_lv<31> calcDistancesHW::ap_ST_fsm_state29 = "10000000000000000000000000000";
const sc_lv<31> calcDistancesHW::ap_ST_fsm_state30 = "100000000000000000000000000000";
const sc_lv<31> calcDistancesHW::ap_ST_fsm_state31 = "1000000000000000000000000000000";
const sc_lv<32> calcDistancesHW::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> calcDistancesHW::ap_const_lv1_1 = "1";
const bool calcDistancesHW::ap_const_boolean_1 = true;
const sc_lv<32> calcDistancesHW::ap_const_lv32_2 = "10";
const sc_lv<1> calcDistancesHW::ap_const_lv1_0 = "0";
const sc_lv<32> calcDistancesHW::ap_const_lv32_1E = "11110";
const sc_lv<32> calcDistancesHW::ap_const_lv32_1 = "1";
const sc_lv<32> calcDistancesHW::ap_const_lv32_3 = "11";
const sc_lv<32> calcDistancesHW::ap_const_lv32_5 = "101";
const sc_lv<32> calcDistancesHW::ap_const_lv32_6 = "110";
const sc_lv<32> calcDistancesHW::ap_const_lv32_7 = "111";
const sc_lv<32> calcDistancesHW::ap_const_lv32_B = "1011";
const sc_lv<32> calcDistancesHW::ap_const_lv32_E = "1110";
const sc_lv<32> calcDistancesHW::ap_const_lv32_12 = "10010";
const sc_lv<32> calcDistancesHW::ap_const_lv32_1B = "11011";
const sc_lv<32> calcDistancesHW::ap_const_lv32_1D = "11101";
const sc_lv<11> calcDistancesHW::ap_const_lv11_0 = "00000000000";
const sc_lv<6> calcDistancesHW::ap_const_lv6_0 = "000000";
const sc_lv<32> calcDistancesHW::ap_const_lv32_4 = "100";
const sc_lv<32> calcDistancesHW::ap_const_lv32_1C = "11100";
const sc_lv<32> calcDistancesHW::ap_const_lv32_8 = "1000";
const sc_lv<32> calcDistancesHW::ap_const_lv32_F = "1111";
const sc_lv<32> calcDistancesHW::ap_const_lv32_C = "1100";
const sc_lv<5> calcDistancesHW::ap_const_lv5_0 = "00000";
const sc_lv<11> calcDistancesHW::ap_const_lv11_400 = "10000000000";
const sc_lv<11> calcDistancesHW::ap_const_lv11_1 = "1";
const sc_lv<6> calcDistancesHW::ap_const_lv6_20 = "100000";
const sc_lv<6> calcDistancesHW::ap_const_lv6_1 = "1";
const sc_lv<2> calcDistancesHW::ap_const_lv2_0 = "00";
const sc_lv<2> calcDistancesHW::ap_const_lv2_1 = "1";

calcDistancesHW::calcDistancesHW(sc_module_name name) : sc_module(name), mVcdFile(0) {
    data_hw_tmp_U = new calcDistancesHW_dbkb("data_hw_tmp_U");
    data_hw_tmp_U->clk(ap_clk);
    data_hw_tmp_U->reset(ap_rst_n_inv);
    data_hw_tmp_U->address0(data_hw_tmp_address0);
    data_hw_tmp_U->ce0(data_hw_tmp_ce0);
    data_hw_tmp_U->we0(data_hw_tmp_we0);
    data_hw_tmp_U->d0(data_hw_dout);
    data_hw_tmp_U->q0(data_hw_tmp_q0);
    movie_tmp_U = new calcDistancesHW_mcud("movie_tmp_U");
    movie_tmp_U->clk(ap_clk);
    movie_tmp_U->reset(ap_rst_n_inv);
    movie_tmp_U->address0(movie_tmp_address0);
    movie_tmp_U->ce0(movie_tmp_ce0);
    movie_tmp_U->we0(movie_tmp_we0);
    movie_tmp_U->d0(data_hw_tmp_q0);
    movie_tmp_U->q0(movie_tmp_q0);
    dists_hw_tmp_U = new calcDistancesHW_ddEe("dists_hw_tmp_U");
    dists_hw_tmp_U->clk(ap_clk);
    dists_hw_tmp_U->reset(ap_rst_n_inv);
    dists_hw_tmp_U->address0(dists_hw_tmp_address0);
    dists_hw_tmp_U->ce0(dists_hw_tmp_ce0);
    dists_hw_tmp_U->we0(dists_hw_tmp_we0);
    dists_hw_tmp_U->d0(tmp_6_reg_494);
    dists_hw_tmp_U->q0(dists_hw_tmp_q0);
    calcDistancesHW_feOg_U1 = new calcDistancesHW_feOg<1,4,32,32,32>("calcDistancesHW_feOg_U1");
    calcDistancesHW_feOg_U1->clk(ap_clk);
    calcDistancesHW_feOg_U1->reset(ap_rst_n_inv);
    calcDistancesHW_feOg_U1->din0(grp_fu_235_p0);
    calcDistancesHW_feOg_U1->din1(grp_fu_235_p1);
    calcDistancesHW_feOg_U1->opcode(grp_fu_235_opcode);
    calcDistancesHW_feOg_U1->ce(ap_var_for_const0);
    calcDistancesHW_feOg_U1->dout(grp_fu_235_p2);
    calcDistancesHW_ffYi_U2 = new calcDistancesHW_ffYi<1,3,32,32,32>("calcDistancesHW_ffYi_U2");
    calcDistancesHW_ffYi_U2->clk(ap_clk);
    calcDistancesHW_ffYi_U2->reset(ap_rst_n_inv);
    calcDistancesHW_ffYi_U2->din0(diff_reg_478);
    calcDistancesHW_ffYi_U2->din1(diff_reg_478);
    calcDistancesHW_ffYi_U2->ce(ap_var_for_const0);
    calcDistancesHW_ffYi_U2->dout(grp_fu_240_p2);
    calcDistancesHW_fg8j_U3 = new calcDistancesHW_fg8j<1,10,32,32,32>("calcDistancesHW_fg8j_U3");
    calcDistancesHW_fg8j_U3->clk(ap_clk);
    calcDistancesHW_fg8j_U3->reset(ap_rst_n_inv);
    calcDistancesHW_fg8j_U3->din0(ap_var_for_const1);
    calcDistancesHW_fg8j_U3->din1(sum_reg_201);
    calcDistancesHW_fg8j_U3->ce(ap_var_for_const0);
    calcDistancesHW_fg8j_U3->dout(grp_fu_244_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state15);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state16);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state19);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state28);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state29);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state30);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state31);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state3);
    sensitive << ( data_hw_empty_n );
    sensitive << ( exitcond4_fu_288_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state30 );
    sensitive << ( exitcond_fu_381_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state30 );
    sensitive << ( exitcond_fu_381_p2 );

    SC_METHOD(thread_ap_rst_n_inv);
    sensitive << ( ap_rst_n );

    SC_METHOD(thread_data_hw_blk_n);
    sensitive << ( data_hw_empty_n );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( exitcond4_fu_288_p2 );

    SC_METHOD(thread_data_hw_read);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( exitcond4_fu_288_p2 );
    sensitive << ( ap_block_state3 );

    SC_METHOD(thread_data_hw_tmp_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( i1_cast4_fu_300_p1 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( tmp_8_cast_fu_283_p1 );
    sensitive << ( tmp_12_cast_fu_359_p1 );

    SC_METHOD(thread_data_hw_tmp_ce0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_block_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_data_hw_tmp_we0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( exitcond4_fu_288_p2 );
    sensitive << ( ap_block_state3 );

    SC_METHOD(thread_dists_hw_blk_n);
    sensitive << ( dists_hw_full_n );
    sensitive << ( ap_CS_fsm_state31 );

    SC_METHOD(thread_dists_hw_din);
    sensitive << ( dists_hw_full_n );
    sensitive << ( ap_CS_fsm_state31 );
    sensitive << ( dists_hw_tmp_q0 );

    SC_METHOD(thread_dists_hw_tmp_address0);
    sensitive << ( i2_cast3_reg_432 );
    sensitive << ( ap_CS_fsm_state30 );
    sensitive << ( ap_CS_fsm_state29 );
    sensitive << ( i4_cast1_fu_376_p1 );

    SC_METHOD(thread_dists_hw_tmp_ce0);
    sensitive << ( ap_CS_fsm_state30 );
    sensitive << ( ap_CS_fsm_state29 );

    SC_METHOD(thread_dists_hw_tmp_we0);
    sensitive << ( ap_CS_fsm_state29 );

    SC_METHOD(thread_dists_hw_write);
    sensitive << ( dists_hw_full_n );
    sensitive << ( ap_CS_fsm_state31 );

    SC_METHOD(thread_exitcond1_fu_364_p2);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( j3_reg_213 );

    SC_METHOD(thread_exitcond2_fu_333_p2);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( i2_reg_190 );

    SC_METHOD(thread_exitcond3_fu_305_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( i1_reg_179 );

    SC_METHOD(thread_exitcond4_fu_288_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_block_state3 );
    sensitive << ( j_reg_168 );

    SC_METHOD(thread_exitcond5_fu_262_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_reg_157 );

    SC_METHOD(thread_exitcond_fu_381_p2);
    sensitive << ( ap_CS_fsm_state30 );
    sensitive << ( i4_reg_224 );

    SC_METHOD(thread_grp_fu_235_opcode);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_grp_fu_235_p0);
    sensitive << ( data_hw_tmp_load_1_reg_468 );
    sensitive << ( sum_reg_201 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_grp_fu_235_p1);
    sensitive << ( movie_tmp_load_reg_473 );
    sensitive << ( tmp_9_reg_484 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_i1_cast4_fu_300_p1);
    sensitive << ( i1_reg_179 );

    SC_METHOD(thread_i2_cast3_fu_317_p1);
    sensitive << ( i2_reg_190 );

    SC_METHOD(thread_i4_cast1_fu_376_p1);
    sensitive << ( i4_reg_224 );

    SC_METHOD(thread_i_1_fu_311_p2);
    sensitive << ( i1_reg_179 );

    SC_METHOD(thread_i_2_fu_268_p2);
    sensitive << ( i_reg_157 );

    SC_METHOD(thread_i_3_fu_387_p2);
    sensitive << ( i4_reg_224 );

    SC_METHOD(thread_i_4_fu_339_p2);
    sensitive << ( i2_reg_190 );

    SC_METHOD(thread_j3_cast2_cast_fu_350_p1);
    sensitive << ( j3_reg_213 );

    SC_METHOD(thread_j3_cast2_fu_345_p1);
    sensitive << ( j3_reg_213 );

    SC_METHOD(thread_j_1_fu_294_p2);
    sensitive << ( j_reg_168 );

    SC_METHOD(thread_j_2_fu_370_p2);
    sensitive << ( j3_reg_213 );

    SC_METHOD(thread_j_cast5_cast_fu_274_p1);
    sensitive << ( j_reg_168 );

    SC_METHOD(thread_movie_tmp_address0);
    sensitive << ( i1_cast4_reg_414 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( j3_cast2_fu_345_p1 );

    SC_METHOD(thread_movie_tmp_ce0);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_movie_tmp_we0);
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_tmp_11_cast_fu_329_p1);
    sensitive << ( tmp_s_fu_321_p3 );

    SC_METHOD(thread_tmp_12_cast_fu_359_p1);
    sensitive << ( tmp_3_fu_354_p2 );

    SC_METHOD(thread_tmp_3_fu_354_p2);
    sensitive << ( tmp_11_cast_reg_437 );
    sensitive << ( j3_cast2_cast_fu_350_p1 );

    SC_METHOD(thread_tmp_4_fu_250_p3);
    sensitive << ( i_reg_157 );

    SC_METHOD(thread_tmp_5_cast_fu_258_p1);
    sensitive << ( tmp_4_fu_250_p3 );

    SC_METHOD(thread_tmp_8_cast_fu_283_p1);
    sensitive << ( tmp_8_fu_278_p2 );

    SC_METHOD(thread_tmp_8_fu_278_p2);
    sensitive << ( tmp_5_cast_reg_393 );
    sensitive << ( j_cast5_cast_fu_274_p1 );

    SC_METHOD(thread_tmp_s_fu_321_p3);
    sensitive << ( i2_reg_190 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( dists_hw_full_n );
    sensitive << ( exitcond4_fu_288_p2 );
    sensitive << ( ap_block_state3 );
    sensitive << ( exitcond1_fu_364_p2 );
    sensitive << ( exitcond_fu_381_p2 );
    sensitive << ( exitcond5_fu_262_p2 );
    sensitive << ( exitcond3_fu_305_p2 );
    sensitive << ( exitcond2_fu_333_p2 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    SC_THREAD(thread_ap_var_for_const1);

    ap_CS_fsm = "0000000000000000000000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "calcDistancesHW_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst_n, "(port)ap_rst_n");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, data_hw_dout, "(port)data_hw_dout");
    sc_trace(mVcdFile, data_hw_empty_n, "(port)data_hw_empty_n");
    sc_trace(mVcdFile, data_hw_read, "(port)data_hw_read");
    sc_trace(mVcdFile, dists_hw_din, "(port)dists_hw_din");
    sc_trace(mVcdFile, dists_hw_full_n, "(port)dists_hw_full_n");
    sc_trace(mVcdFile, dists_hw_write, "(port)dists_hw_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_rst_n_inv, "ap_rst_n_inv");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, data_hw_blk_n, "data_hw_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, exitcond4_fu_288_p2, "exitcond4_fu_288_p2");
    sc_trace(mVcdFile, dists_hw_blk_n, "dists_hw_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_state31, "ap_CS_fsm_state31");
    sc_trace(mVcdFile, tmp_5_cast_fu_258_p1, "tmp_5_cast_fu_258_p1");
    sc_trace(mVcdFile, tmp_5_cast_reg_393, "tmp_5_cast_reg_393");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, i_2_fu_268_p2, "i_2_fu_268_p2");
    sc_trace(mVcdFile, i_2_reg_401, "i_2_reg_401");
    sc_trace(mVcdFile, j_1_fu_294_p2, "j_1_fu_294_p2");
    sc_trace(mVcdFile, ap_block_state3, "ap_block_state3");
    sc_trace(mVcdFile, i1_cast4_fu_300_p1, "i1_cast4_fu_300_p1");
    sc_trace(mVcdFile, i1_cast4_reg_414, "i1_cast4_reg_414");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, i_1_fu_311_p2, "i_1_fu_311_p2");
    sc_trace(mVcdFile, i_1_reg_427, "i_1_reg_427");
    sc_trace(mVcdFile, i2_cast3_fu_317_p1, "i2_cast3_fu_317_p1");
    sc_trace(mVcdFile, i2_cast3_reg_432, "i2_cast3_reg_432");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, tmp_11_cast_fu_329_p1, "tmp_11_cast_fu_329_p1");
    sc_trace(mVcdFile, tmp_11_cast_reg_437, "tmp_11_cast_reg_437");
    sc_trace(mVcdFile, i_4_fu_339_p2, "i_4_fu_339_p2");
    sc_trace(mVcdFile, i_4_reg_445, "i_4_reg_445");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, j_2_fu_370_p2, "j_2_fu_370_p2");
    sc_trace(mVcdFile, j_2_reg_458, "j_2_reg_458");
    sc_trace(mVcdFile, exitcond1_fu_364_p2, "exitcond1_fu_364_p2");
    sc_trace(mVcdFile, data_hw_tmp_q0, "data_hw_tmp_q0");
    sc_trace(mVcdFile, data_hw_tmp_load_1_reg_468, "data_hw_tmp_load_1_reg_468");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, movie_tmp_q0, "movie_tmp_q0");
    sc_trace(mVcdFile, movie_tmp_load_reg_473, "movie_tmp_load_reg_473");
    sc_trace(mVcdFile, grp_fu_235_p2, "grp_fu_235_p2");
    sc_trace(mVcdFile, diff_reg_478, "diff_reg_478");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, grp_fu_240_p2, "grp_fu_240_p2");
    sc_trace(mVcdFile, tmp_9_reg_484, "tmp_9_reg_484");
    sc_trace(mVcdFile, ap_CS_fsm_state15, "ap_CS_fsm_state15");
    sc_trace(mVcdFile, ap_CS_fsm_state19, "ap_CS_fsm_state19");
    sc_trace(mVcdFile, grp_fu_244_p2, "grp_fu_244_p2");
    sc_trace(mVcdFile, tmp_6_reg_494, "tmp_6_reg_494");
    sc_trace(mVcdFile, ap_CS_fsm_state28, "ap_CS_fsm_state28");
    sc_trace(mVcdFile, i_3_fu_387_p2, "i_3_fu_387_p2");
    sc_trace(mVcdFile, i_3_reg_502, "i_3_reg_502");
    sc_trace(mVcdFile, ap_CS_fsm_state30, "ap_CS_fsm_state30");
    sc_trace(mVcdFile, exitcond_fu_381_p2, "exitcond_fu_381_p2");
    sc_trace(mVcdFile, data_hw_tmp_address0, "data_hw_tmp_address0");
    sc_trace(mVcdFile, data_hw_tmp_ce0, "data_hw_tmp_ce0");
    sc_trace(mVcdFile, data_hw_tmp_we0, "data_hw_tmp_we0");
    sc_trace(mVcdFile, movie_tmp_address0, "movie_tmp_address0");
    sc_trace(mVcdFile, movie_tmp_ce0, "movie_tmp_ce0");
    sc_trace(mVcdFile, movie_tmp_we0, "movie_tmp_we0");
    sc_trace(mVcdFile, dists_hw_tmp_address0, "dists_hw_tmp_address0");
    sc_trace(mVcdFile, dists_hw_tmp_ce0, "dists_hw_tmp_ce0");
    sc_trace(mVcdFile, dists_hw_tmp_we0, "dists_hw_tmp_we0");
    sc_trace(mVcdFile, dists_hw_tmp_q0, "dists_hw_tmp_q0");
    sc_trace(mVcdFile, i_reg_157, "i_reg_157");
    sc_trace(mVcdFile, j_reg_168, "j_reg_168");
    sc_trace(mVcdFile, exitcond5_fu_262_p2, "exitcond5_fu_262_p2");
    sc_trace(mVcdFile, i1_reg_179, "i1_reg_179");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, i2_reg_190, "i2_reg_190");
    sc_trace(mVcdFile, ap_CS_fsm_state29, "ap_CS_fsm_state29");
    sc_trace(mVcdFile, exitcond3_fu_305_p2, "exitcond3_fu_305_p2");
    sc_trace(mVcdFile, sum_reg_201, "sum_reg_201");
    sc_trace(mVcdFile, exitcond2_fu_333_p2, "exitcond2_fu_333_p2");
    sc_trace(mVcdFile, j3_reg_213, "j3_reg_213");
    sc_trace(mVcdFile, i4_reg_224, "i4_reg_224");
    sc_trace(mVcdFile, tmp_8_cast_fu_283_p1, "tmp_8_cast_fu_283_p1");
    sc_trace(mVcdFile, tmp_12_cast_fu_359_p1, "tmp_12_cast_fu_359_p1");
    sc_trace(mVcdFile, j3_cast2_fu_345_p1, "j3_cast2_fu_345_p1");
    sc_trace(mVcdFile, i4_cast1_fu_376_p1, "i4_cast1_fu_376_p1");
    sc_trace(mVcdFile, grp_fu_235_p0, "grp_fu_235_p0");
    sc_trace(mVcdFile, grp_fu_235_p1, "grp_fu_235_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, ap_CS_fsm_state16, "ap_CS_fsm_state16");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, tmp_4_fu_250_p3, "tmp_4_fu_250_p3");
    sc_trace(mVcdFile, j_cast5_cast_fu_274_p1, "j_cast5_cast_fu_274_p1");
    sc_trace(mVcdFile, tmp_8_fu_278_p2, "tmp_8_fu_278_p2");
    sc_trace(mVcdFile, tmp_s_fu_321_p3, "tmp_s_fu_321_p3");
    sc_trace(mVcdFile, j3_cast2_cast_fu_350_p1, "j3_cast2_cast_fu_350_p1");
    sc_trace(mVcdFile, tmp_3_fu_354_p2, "tmp_3_fu_354_p2");
    sc_trace(mVcdFile, grp_fu_235_opcode, "grp_fu_235_opcode");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("calcDistancesHW.hdltvin.dat");
    mHdltvoutHandle.open("calcDistancesHW.hdltvout.dat");
}

calcDistancesHW::~calcDistancesHW() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete data_hw_tmp_U;
    delete movie_tmp_U;
    delete dists_hw_tmp_U;
    delete calcDistancesHW_feOg_U1;
    delete calcDistancesHW_ffYi_U2;
    delete calcDistancesHW_fg8j_U3;
}

void calcDistancesHW::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void calcDistancesHW::thread_ap_var_for_const1() {
    ap_var_for_const1 = ap_const_lv32_0;
}

void calcDistancesHW::thread_ap_clk_no_reset_() {
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state2.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond5_fu_262_p2.read()))) {
        i1_reg_179 = ap_const_lv6_0;
    } else if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state5.read())) {
        i1_reg_179 = i_1_reg_427.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state4.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_305_p2.read()))) {
        i2_reg_190 = ap_const_lv11_0;
    } else if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state29.read())) {
        i2_reg_190 = i_4_reg_445.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state6.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_333_p2.read()))) {
        i4_reg_224 = ap_const_lv11_0;
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state31.read()) && 
                !esl_seteq<1,1,1>(ap_const_logic_0, dists_hw_full_n.read()))) {
        i4_reg_224 = i_3_reg_502.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state3.read()) && 
         !esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state3.read()) && 
         !esl_seteq<1,1,1>(exitcond4_fu_288_p2.read(), ap_const_lv1_0))) {
        i_reg_157 = i_2_reg_401.read();
    } else if ((esl_seteq<1,1,1>(ap_CS_fsm_state1.read(), ap_const_lv1_1) && 
                !esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()))) {
        i_reg_157 = ap_const_lv11_0;
    }
    if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state19.read())) {
        j3_reg_213 = j_2_reg_458.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state6.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_333_p2.read()))) {
        j3_reg_213 = ap_const_lv6_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(exitcond4_fu_288_p2.read(), ap_const_lv1_0) && 
         !esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state3.read()))) {
        j_reg_168 = j_1_fu_294_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond5_fu_262_p2.read()))) {
        j_reg_168 = ap_const_lv6_0;
    }
    if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state19.read())) {
        sum_reg_201 = grp_fu_235_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state6.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_333_p2.read()))) {
        sum_reg_201 = ap_const_lv32_0;
    }
    if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state8.read())) {
        data_hw_tmp_load_1_reg_468 = data_hw_tmp_q0.read();
        movie_tmp_load_reg_473 = movie_tmp_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state12.read())) {
        diff_reg_478 = grp_fu_235_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state4.read())) {
        i1_cast4_reg_414 = i1_cast4_fu_300_p1.read();
        i_1_reg_427 = i_1_fu_311_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state6.read())) {
        i2_cast3_reg_432 = i2_cast3_fu_317_p1.read();
        i_4_reg_445 = i_4_fu_339_p2.read();
        tmp_11_cast_reg_437 = tmp_11_cast_fu_329_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state2.read())) {
        i_2_reg_401 = i_2_fu_268_p2.read();
        tmp_5_cast_reg_393 = tmp_5_cast_fu_258_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state30.read())) {
        i_3_reg_502 = i_3_fu_387_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state7.read())) {
        j_2_reg_458 = j_2_fu_370_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state28.read())) {
        tmp_6_reg_494 = grp_fu_244_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state15.read())) {
        tmp_9_reg_484 = grp_fu_240_p2.read();
    }
}

void calcDistancesHW::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read().range(0, 0);
}

void calcDistancesHW::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read().range(11, 11);
}

void calcDistancesHW::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read().range(12, 12);
}

void calcDistancesHW::thread_ap_CS_fsm_state15() {
    ap_CS_fsm_state15 = ap_CS_fsm.read().range(14, 14);
}

void calcDistancesHW::thread_ap_CS_fsm_state16() {
    ap_CS_fsm_state16 = ap_CS_fsm.read().range(15, 15);
}

void calcDistancesHW::thread_ap_CS_fsm_state19() {
    ap_CS_fsm_state19 = ap_CS_fsm.read().range(18, 18);
}

void calcDistancesHW::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read().range(1, 1);
}

void calcDistancesHW::thread_ap_CS_fsm_state28() {
    ap_CS_fsm_state28 = ap_CS_fsm.read().range(27, 27);
}

void calcDistancesHW::thread_ap_CS_fsm_state29() {
    ap_CS_fsm_state29 = ap_CS_fsm.read().range(28, 28);
}

void calcDistancesHW::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read().range(2, 2);
}

void calcDistancesHW::thread_ap_CS_fsm_state30() {
    ap_CS_fsm_state30 = ap_CS_fsm.read().range(29, 29);
}

void calcDistancesHW::thread_ap_CS_fsm_state31() {
    ap_CS_fsm_state31 = ap_CS_fsm.read().range(30, 30);
}

void calcDistancesHW::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read().range(3, 3);
}

void calcDistancesHW::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read().range(4, 4);
}

void calcDistancesHW::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read().range(5, 5);
}

void calcDistancesHW::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read().range(6, 6);
}

void calcDistancesHW::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read().range(7, 7);
}

void calcDistancesHW::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read().range(8, 8);
}

void calcDistancesHW::thread_ap_block_state3() {
    ap_block_state3 = (esl_seteq<1,1,1>(exitcond4_fu_288_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, data_hw_empty_n.read()));
}

void calcDistancesHW::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state30.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_381_p2.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void calcDistancesHW::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_CS_fsm_state1.read(), ap_const_lv1_1))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void calcDistancesHW::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state30.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_381_p2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void calcDistancesHW::thread_ap_rst_n_inv() {
    ap_rst_n_inv =  (sc_logic) (~ap_rst_n.read());
}

void calcDistancesHW::thread_data_hw_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(exitcond4_fu_288_p2.read(), ap_const_lv1_0))) {
        data_hw_blk_n = data_hw_empty_n.read();
    } else {
        data_hw_blk_n = ap_const_logic_1;
    }
}

void calcDistancesHW::thread_data_hw_read() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(exitcond4_fu_288_p2.read(), ap_const_lv1_0) && 
         !esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state3.read()))) {
        data_hw_read = ap_const_logic_1;
    } else {
        data_hw_read = ap_const_logic_0;
    }
}

void calcDistancesHW::thread_data_hw_tmp_address0() {
    if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state7.read())) {
        data_hw_tmp_address0 =  (sc_lv<15>) (tmp_12_cast_fu_359_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state4.read())) {
        data_hw_tmp_address0 =  (sc_lv<15>) (i1_cast4_fu_300_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state3.read())) {
        data_hw_tmp_address0 =  (sc_lv<15>) (tmp_8_cast_fu_283_p1.read());
    } else {
        data_hw_tmp_address0 = "XXXXXXXXXXXXXXX";
    }
}

void calcDistancesHW::thread_data_hw_tmp_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state3.read()) && 
          !esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state3.read())) || 
         esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state7.read()))) {
        data_hw_tmp_ce0 = ap_const_logic_1;
    } else {
        data_hw_tmp_ce0 = ap_const_logic_0;
    }
}

void calcDistancesHW::thread_data_hw_tmp_we0() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(exitcond4_fu_288_p2.read(), ap_const_lv1_0) && 
         !esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state3.read()))) {
        data_hw_tmp_we0 = ap_const_logic_1;
    } else {
        data_hw_tmp_we0 = ap_const_logic_0;
    }
}

void calcDistancesHW::thread_dists_hw_blk_n() {
    if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state31.read())) {
        dists_hw_blk_n = dists_hw_full_n.read();
    } else {
        dists_hw_blk_n = ap_const_logic_1;
    }
}

void calcDistancesHW::thread_dists_hw_din() {
    dists_hw_din = dists_hw_tmp_q0.read();
}

void calcDistancesHW::thread_dists_hw_tmp_address0() {
    if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state30.read())) {
        dists_hw_tmp_address0 =  (sc_lv<10>) (i4_cast1_fu_376_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state29.read())) {
        dists_hw_tmp_address0 =  (sc_lv<10>) (i2_cast3_reg_432.read());
    } else {
        dists_hw_tmp_address0 =  (sc_lv<10>) ("XXXXXXXXXX");
    }
}

void calcDistancesHW::thread_dists_hw_tmp_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state30.read()) || 
         esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state29.read()))) {
        dists_hw_tmp_ce0 = ap_const_logic_1;
    } else {
        dists_hw_tmp_ce0 = ap_const_logic_0;
    }
}

void calcDistancesHW::thread_dists_hw_tmp_we0() {
    if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state29.read())) {
        dists_hw_tmp_we0 = ap_const_logic_1;
    } else {
        dists_hw_tmp_we0 = ap_const_logic_0;
    }
}

void calcDistancesHW::thread_dists_hw_write() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state31.read()) && 
         !esl_seteq<1,1,1>(ap_const_logic_0, dists_hw_full_n.read()))) {
        dists_hw_write = ap_const_logic_1;
    } else {
        dists_hw_write = ap_const_logic_0;
    }
}

void calcDistancesHW::thread_exitcond1_fu_364_p2() {
    exitcond1_fu_364_p2 = (!j3_reg_213.read().is_01() || !ap_const_lv6_20.is_01())? sc_lv<1>(): sc_lv<1>(j3_reg_213.read() == ap_const_lv6_20);
}

void calcDistancesHW::thread_exitcond2_fu_333_p2() {
    exitcond2_fu_333_p2 = (!i2_reg_190.read().is_01() || !ap_const_lv11_400.is_01())? sc_lv<1>(): sc_lv<1>(i2_reg_190.read() == ap_const_lv11_400);
}

void calcDistancesHW::thread_exitcond3_fu_305_p2() {
    exitcond3_fu_305_p2 = (!i1_reg_179.read().is_01() || !ap_const_lv6_20.is_01())? sc_lv<1>(): sc_lv<1>(i1_reg_179.read() == ap_const_lv6_20);
}

void calcDistancesHW::thread_exitcond4_fu_288_p2() {
    exitcond4_fu_288_p2 = (!j_reg_168.read().is_01() || !ap_const_lv6_20.is_01())? sc_lv<1>(): sc_lv<1>(j_reg_168.read() == ap_const_lv6_20);
}

void calcDistancesHW::thread_exitcond5_fu_262_p2() {
    exitcond5_fu_262_p2 = (!i_reg_157.read().is_01() || !ap_const_lv11_400.is_01())? sc_lv<1>(): sc_lv<1>(i_reg_157.read() == ap_const_lv11_400);
}

void calcDistancesHW::thread_exitcond_fu_381_p2() {
    exitcond_fu_381_p2 = (!i4_reg_224.read().is_01() || !ap_const_lv11_400.is_01())? sc_lv<1>(): sc_lv<1>(i4_reg_224.read() == ap_const_lv11_400);
}

void calcDistancesHW::thread_grp_fu_235_opcode() {
    if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state9.read())) {
        grp_fu_235_opcode = ap_const_lv2_1;
    } else if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state16.read())) {
        grp_fu_235_opcode = ap_const_lv2_0;
    } else {
        grp_fu_235_opcode =  (sc_lv<2>) ("XX");
    }
}

void calcDistancesHW::thread_grp_fu_235_p0() {
    if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state16.read())) {
        grp_fu_235_p0 = sum_reg_201.read();
    } else if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state9.read())) {
        grp_fu_235_p0 = data_hw_tmp_load_1_reg_468.read();
    } else {
        grp_fu_235_p0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void calcDistancesHW::thread_grp_fu_235_p1() {
    if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state16.read())) {
        grp_fu_235_p1 = tmp_9_reg_484.read();
    } else if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state9.read())) {
        grp_fu_235_p1 = movie_tmp_load_reg_473.read();
    } else {
        grp_fu_235_p1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void calcDistancesHW::thread_i1_cast4_fu_300_p1() {
    i1_cast4_fu_300_p1 = esl_zext<32,6>(i1_reg_179.read());
}

void calcDistancesHW::thread_i2_cast3_fu_317_p1() {
    i2_cast3_fu_317_p1 = esl_zext<32,11>(i2_reg_190.read());
}

void calcDistancesHW::thread_i4_cast1_fu_376_p1() {
    i4_cast1_fu_376_p1 = esl_zext<32,11>(i4_reg_224.read());
}

void calcDistancesHW::thread_i_1_fu_311_p2() {
    i_1_fu_311_p2 = (!i1_reg_179.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<6>(): (sc_biguint<6>(i1_reg_179.read()) + sc_biguint<6>(ap_const_lv6_1));
}

void calcDistancesHW::thread_i_2_fu_268_p2() {
    i_2_fu_268_p2 = (!i_reg_157.read().is_01() || !ap_const_lv11_1.is_01())? sc_lv<11>(): (sc_biguint<11>(i_reg_157.read()) + sc_biguint<11>(ap_const_lv11_1));
}

void calcDistancesHW::thread_i_3_fu_387_p2() {
    i_3_fu_387_p2 = (!i4_reg_224.read().is_01() || !ap_const_lv11_1.is_01())? sc_lv<11>(): (sc_biguint<11>(i4_reg_224.read()) + sc_biguint<11>(ap_const_lv11_1));
}

void calcDistancesHW::thread_i_4_fu_339_p2() {
    i_4_fu_339_p2 = (!i2_reg_190.read().is_01() || !ap_const_lv11_1.is_01())? sc_lv<11>(): (sc_biguint<11>(i2_reg_190.read()) + sc_biguint<11>(ap_const_lv11_1));
}

void calcDistancesHW::thread_j3_cast2_cast_fu_350_p1() {
    j3_cast2_cast_fu_350_p1 = esl_zext<17,6>(j3_reg_213.read());
}

void calcDistancesHW::thread_j3_cast2_fu_345_p1() {
    j3_cast2_fu_345_p1 = esl_zext<32,6>(j3_reg_213.read());
}

void calcDistancesHW::thread_j_1_fu_294_p2() {
    j_1_fu_294_p2 = (!j_reg_168.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<6>(): (sc_biguint<6>(j_reg_168.read()) + sc_biguint<6>(ap_const_lv6_1));
}

void calcDistancesHW::thread_j_2_fu_370_p2() {
    j_2_fu_370_p2 = (!j3_reg_213.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<6>(): (sc_biguint<6>(j3_reg_213.read()) + sc_biguint<6>(ap_const_lv6_1));
}

void calcDistancesHW::thread_j_cast5_cast_fu_274_p1() {
    j_cast5_cast_fu_274_p1 = esl_zext<17,6>(j_reg_168.read());
}

void calcDistancesHW::thread_movie_tmp_address0() {
    if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state7.read())) {
        movie_tmp_address0 =  (sc_lv<5>) (j3_cast2_fu_345_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state5.read())) {
        movie_tmp_address0 =  (sc_lv<5>) (i1_cast4_reg_414.read());
    } else {
        movie_tmp_address0 =  (sc_lv<5>) ("XXXXX");
    }
}

void calcDistancesHW::thread_movie_tmp_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state5.read()))) {
        movie_tmp_ce0 = ap_const_logic_1;
    } else {
        movie_tmp_ce0 = ap_const_logic_0;
    }
}

void calcDistancesHW::thread_movie_tmp_we0() {
    if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state5.read())) {
        movie_tmp_we0 = ap_const_logic_1;
    } else {
        movie_tmp_we0 = ap_const_logic_0;
    }
}

void calcDistancesHW::thread_tmp_11_cast_fu_329_p1() {
    tmp_11_cast_fu_329_p1 = esl_zext<17,16>(tmp_s_fu_321_p3.read());
}

void calcDistancesHW::thread_tmp_12_cast_fu_359_p1() {
    tmp_12_cast_fu_359_p1 = esl_zext<32,17>(tmp_3_fu_354_p2.read());
}

void calcDistancesHW::thread_tmp_3_fu_354_p2() {
    tmp_3_fu_354_p2 = (!tmp_11_cast_reg_437.read().is_01() || !j3_cast2_cast_fu_350_p1.read().is_01())? sc_lv<17>(): (sc_biguint<17>(tmp_11_cast_reg_437.read()) + sc_biguint<17>(j3_cast2_cast_fu_350_p1.read()));
}

void calcDistancesHW::thread_tmp_4_fu_250_p3() {
    tmp_4_fu_250_p3 = esl_concat<11,5>(i_reg_157.read(), ap_const_lv5_0);
}

void calcDistancesHW::thread_tmp_5_cast_fu_258_p1() {
    tmp_5_cast_fu_258_p1 = esl_zext<17,16>(tmp_4_fu_250_p3.read());
}

void calcDistancesHW::thread_tmp_8_cast_fu_283_p1() {
    tmp_8_cast_fu_283_p1 = esl_zext<32,17>(tmp_8_fu_278_p2.read());
}

void calcDistancesHW::thread_tmp_8_fu_278_p2() {
    tmp_8_fu_278_p2 = (!tmp_5_cast_reg_393.read().is_01() || !j_cast5_cast_fu_274_p1.read().is_01())? sc_lv<17>(): (sc_biguint<17>(tmp_5_cast_reg_393.read()) + sc_biguint<17>(j_cast5_cast_fu_274_p1.read()));
}

void calcDistancesHW::thread_tmp_s_fu_321_p3() {
    tmp_s_fu_321_p3 = esl_concat<11,5>(i2_reg_190.read(), ap_const_lv5_0);
}

void calcDistancesHW::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read())) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond5_fu_262_p2.read())) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            if ((!esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state3.read()) && !esl_seteq<1,1,1>(exitcond4_fu_288_p2.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else if ((esl_seteq<1,1,1>(exitcond4_fu_288_p2.read(), ap_const_lv1_0) && !esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state3.read()))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 8 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_305_p2.read())) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 32 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_333_p2.read())) {
                ap_NS_fsm = ap_ST_fsm_state30;
            } else {
                ap_NS_fsm = ap_ST_fsm_state7;
            }
            break;
        case 64 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_364_p2.read())) {
                ap_NS_fsm = ap_ST_fsm_state20;
            } else {
                ap_NS_fsm = ap_ST_fsm_state8;
            }
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_fsm_state16;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_fsm_state17;
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_fsm_state18;
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_fsm_state19;
            break;
        case 262144 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 524288 : 
            ap_NS_fsm = ap_ST_fsm_state21;
            break;
        case 1048576 : 
            ap_NS_fsm = ap_ST_fsm_state22;
            break;
        case 2097152 : 
            ap_NS_fsm = ap_ST_fsm_state23;
            break;
        case 4194304 : 
            ap_NS_fsm = ap_ST_fsm_state24;
            break;
        case 8388608 : 
            ap_NS_fsm = ap_ST_fsm_state25;
            break;
        case 16777216 : 
            ap_NS_fsm = ap_ST_fsm_state26;
            break;
        case 33554432 : 
            ap_NS_fsm = ap_ST_fsm_state27;
            break;
        case 67108864 : 
            ap_NS_fsm = ap_ST_fsm_state28;
            break;
        case 134217728 : 
            ap_NS_fsm = ap_ST_fsm_state29;
            break;
        case 268435456 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 536870912 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_381_p2.read())) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state31;
            }
            break;
        case 1073741824 : 
            if (!esl_seteq<1,1,1>(ap_const_logic_0, dists_hw_full_n.read())) {
                ap_NS_fsm = ap_ST_fsm_state30;
            } else {
                ap_NS_fsm = ap_ST_fsm_state31;
            }
            break;
        default : 
            ap_NS_fsm =  (sc_lv<31>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
            break;
    }
}

void calcDistancesHW::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst_n\" :  \"" << ap_rst_n.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"data_hw_dout\" :  \"" << data_hw_dout.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"data_hw_empty_n\" :  \"" << data_hw_empty_n.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"data_hw_read\" :  \"" << data_hw_read.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"dists_hw_din\" :  \"" << dists_hw_din.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"dists_hw_full_n\" :  \"" << dists_hw_full_n.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"dists_hw_write\" :  \"" << dists_hw_write.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

