// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _calcDistancesHW_HH_
#define _calcDistancesHW_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "calcDistancesHW_feOg.h"
#include "calcDistancesHW_ffYi.h"
#include "calcDistancesHW_fg8j.h"
#include "calcDistancesHW_dbkb.h"
#include "calcDistancesHW_mcud.h"
#include "calcDistancesHW_ddEe.h"

namespace ap_rtl {

struct calcDistancesHW : public sc_module {
    // Port declarations 12
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst_n;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<32> > data_hw_dout;
    sc_in< sc_logic > data_hw_empty_n;
    sc_out< sc_logic > data_hw_read;
    sc_out< sc_lv<32> > dists_hw_din;
    sc_in< sc_logic > dists_hw_full_n;
    sc_out< sc_logic > dists_hw_write;
    sc_signal< sc_logic > ap_var_for_const0;
    sc_signal< sc_lv<32> > ap_var_for_const1;


    // Module declarations
    calcDistancesHW(sc_module_name name);
    SC_HAS_PROCESS(calcDistancesHW);

    ~calcDistancesHW();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    calcDistancesHW_dbkb* data_hw_tmp_U;
    calcDistancesHW_mcud* movie_tmp_U;
    calcDistancesHW_ddEe* dists_hw_tmp_U;
    calcDistancesHW_feOg<1,4,32,32,32>* calcDistancesHW_feOg_U1;
    calcDistancesHW_ffYi<1,3,32,32,32>* calcDistancesHW_ffYi_U2;
    calcDistancesHW_fg8j<1,10,32,32,32>* calcDistancesHW_fg8j_U3;
    sc_signal< sc_logic > ap_rst_n_inv;
    sc_signal< sc_lv<31> > ap_CS_fsm;
    sc_signal< sc_lv<1> > ap_CS_fsm_state1;
    sc_signal< sc_logic > data_hw_blk_n;
    sc_signal< sc_lv<1> > ap_CS_fsm_state3;
    sc_signal< sc_lv<1> > exitcond4_fu_288_p2;
    sc_signal< sc_logic > dists_hw_blk_n;
    sc_signal< sc_lv<1> > ap_CS_fsm_state31;
    sc_signal< sc_lv<17> > tmp_5_cast_fu_258_p1;
    sc_signal< sc_lv<17> > tmp_5_cast_reg_393;
    sc_signal< sc_lv<1> > ap_CS_fsm_state2;
    sc_signal< sc_lv<11> > i_2_fu_268_p2;
    sc_signal< sc_lv<11> > i_2_reg_401;
    sc_signal< sc_lv<6> > j_1_fu_294_p2;
    sc_signal< bool > ap_block_state3;
    sc_signal< sc_lv<32> > i1_cast4_fu_300_p1;
    sc_signal< sc_lv<32> > i1_cast4_reg_414;
    sc_signal< sc_lv<1> > ap_CS_fsm_state4;
    sc_signal< sc_lv<6> > i_1_fu_311_p2;
    sc_signal< sc_lv<6> > i_1_reg_427;
    sc_signal< sc_lv<32> > i2_cast3_fu_317_p1;
    sc_signal< sc_lv<32> > i2_cast3_reg_432;
    sc_signal< sc_lv<1> > ap_CS_fsm_state6;
    sc_signal< sc_lv<17> > tmp_11_cast_fu_329_p1;
    sc_signal< sc_lv<17> > tmp_11_cast_reg_437;
    sc_signal< sc_lv<11> > i_4_fu_339_p2;
    sc_signal< sc_lv<11> > i_4_reg_445;
    sc_signal< sc_lv<1> > ap_CS_fsm_state7;
    sc_signal< sc_lv<6> > j_2_fu_370_p2;
    sc_signal< sc_lv<6> > j_2_reg_458;
    sc_signal< sc_lv<1> > exitcond1_fu_364_p2;
    sc_signal< sc_lv<32> > data_hw_tmp_q0;
    sc_signal< sc_lv<32> > data_hw_tmp_load_1_reg_468;
    sc_signal< sc_lv<1> > ap_CS_fsm_state8;
    sc_signal< sc_lv<32> > movie_tmp_q0;
    sc_signal< sc_lv<32> > movie_tmp_load_reg_473;
    sc_signal< sc_lv<32> > grp_fu_235_p2;
    sc_signal< sc_lv<32> > diff_reg_478;
    sc_signal< sc_lv<1> > ap_CS_fsm_state12;
    sc_signal< sc_lv<32> > grp_fu_240_p2;
    sc_signal< sc_lv<32> > tmp_9_reg_484;
    sc_signal< sc_lv<1> > ap_CS_fsm_state15;
    sc_signal< sc_lv<1> > ap_CS_fsm_state19;
    sc_signal< sc_lv<32> > grp_fu_244_p2;
    sc_signal< sc_lv<32> > tmp_6_reg_494;
    sc_signal< sc_lv<1> > ap_CS_fsm_state28;
    sc_signal< sc_lv<11> > i_3_fu_387_p2;
    sc_signal< sc_lv<11> > i_3_reg_502;
    sc_signal< sc_lv<1> > ap_CS_fsm_state30;
    sc_signal< sc_lv<1> > exitcond_fu_381_p2;
    sc_signal< sc_lv<15> > data_hw_tmp_address0;
    sc_signal< sc_logic > data_hw_tmp_ce0;
    sc_signal< sc_logic > data_hw_tmp_we0;
    sc_signal< sc_lv<5> > movie_tmp_address0;
    sc_signal< sc_logic > movie_tmp_ce0;
    sc_signal< sc_logic > movie_tmp_we0;
    sc_signal< sc_lv<10> > dists_hw_tmp_address0;
    sc_signal< sc_logic > dists_hw_tmp_ce0;
    sc_signal< sc_logic > dists_hw_tmp_we0;
    sc_signal< sc_lv<32> > dists_hw_tmp_q0;
    sc_signal< sc_lv<11> > i_reg_157;
    sc_signal< sc_lv<6> > j_reg_168;
    sc_signal< sc_lv<1> > exitcond5_fu_262_p2;
    sc_signal< sc_lv<6> > i1_reg_179;
    sc_signal< sc_lv<1> > ap_CS_fsm_state5;
    sc_signal< sc_lv<11> > i2_reg_190;
    sc_signal< sc_lv<1> > ap_CS_fsm_state29;
    sc_signal< sc_lv<1> > exitcond3_fu_305_p2;
    sc_signal< sc_lv<32> > sum_reg_201;
    sc_signal< sc_lv<1> > exitcond2_fu_333_p2;
    sc_signal< sc_lv<6> > j3_reg_213;
    sc_signal< sc_lv<11> > i4_reg_224;
    sc_signal< sc_lv<32> > tmp_8_cast_fu_283_p1;
    sc_signal< sc_lv<32> > tmp_12_cast_fu_359_p1;
    sc_signal< sc_lv<32> > j3_cast2_fu_345_p1;
    sc_signal< sc_lv<32> > i4_cast1_fu_376_p1;
    sc_signal< sc_lv<32> > grp_fu_235_p0;
    sc_signal< sc_lv<32> > grp_fu_235_p1;
    sc_signal< sc_lv<1> > ap_CS_fsm_state9;
    sc_signal< sc_lv<1> > ap_CS_fsm_state16;
    sc_signal< sc_lv<1> > ap_CS_fsm_state13;
    sc_signal< sc_lv<16> > tmp_4_fu_250_p3;
    sc_signal< sc_lv<17> > j_cast5_cast_fu_274_p1;
    sc_signal< sc_lv<17> > tmp_8_fu_278_p2;
    sc_signal< sc_lv<16> > tmp_s_fu_321_p3;
    sc_signal< sc_lv<17> > j3_cast2_cast_fu_350_p1;
    sc_signal< sc_lv<17> > tmp_3_fu_354_p2;
    sc_signal< sc_lv<2> > grp_fu_235_opcode;
    sc_signal< sc_lv<31> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<31> ap_ST_fsm_state1;
    static const sc_lv<31> ap_ST_fsm_state2;
    static const sc_lv<31> ap_ST_fsm_state3;
    static const sc_lv<31> ap_ST_fsm_state4;
    static const sc_lv<31> ap_ST_fsm_state5;
    static const sc_lv<31> ap_ST_fsm_state6;
    static const sc_lv<31> ap_ST_fsm_state7;
    static const sc_lv<31> ap_ST_fsm_state8;
    static const sc_lv<31> ap_ST_fsm_state9;
    static const sc_lv<31> ap_ST_fsm_state10;
    static const sc_lv<31> ap_ST_fsm_state11;
    static const sc_lv<31> ap_ST_fsm_state12;
    static const sc_lv<31> ap_ST_fsm_state13;
    static const sc_lv<31> ap_ST_fsm_state14;
    static const sc_lv<31> ap_ST_fsm_state15;
    static const sc_lv<31> ap_ST_fsm_state16;
    static const sc_lv<31> ap_ST_fsm_state17;
    static const sc_lv<31> ap_ST_fsm_state18;
    static const sc_lv<31> ap_ST_fsm_state19;
    static const sc_lv<31> ap_ST_fsm_state20;
    static const sc_lv<31> ap_ST_fsm_state21;
    static const sc_lv<31> ap_ST_fsm_state22;
    static const sc_lv<31> ap_ST_fsm_state23;
    static const sc_lv<31> ap_ST_fsm_state24;
    static const sc_lv<31> ap_ST_fsm_state25;
    static const sc_lv<31> ap_ST_fsm_state26;
    static const sc_lv<31> ap_ST_fsm_state27;
    static const sc_lv<31> ap_ST_fsm_state28;
    static const sc_lv<31> ap_ST_fsm_state29;
    static const sc_lv<31> ap_ST_fsm_state30;
    static const sc_lv<31> ap_ST_fsm_state31;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const bool ap_const_boolean_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_1E;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<32> ap_const_lv32_B;
    static const sc_lv<32> ap_const_lv32_E;
    static const sc_lv<32> ap_const_lv32_12;
    static const sc_lv<32> ap_const_lv32_1B;
    static const sc_lv<32> ap_const_lv32_1D;
    static const sc_lv<11> ap_const_lv11_0;
    static const sc_lv<6> ap_const_lv6_0;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_1C;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_F;
    static const sc_lv<32> ap_const_lv32_C;
    static const sc_lv<5> ap_const_lv5_0;
    static const sc_lv<11> ap_const_lv11_400;
    static const sc_lv<11> ap_const_lv11_1;
    static const sc_lv<6> ap_const_lv6_20;
    static const sc_lv<6> ap_const_lv6_1;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<2> ap_const_lv2_1;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_var_for_const1();
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state12();
    void thread_ap_CS_fsm_state13();
    void thread_ap_CS_fsm_state15();
    void thread_ap_CS_fsm_state16();
    void thread_ap_CS_fsm_state19();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state28();
    void thread_ap_CS_fsm_state29();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state30();
    void thread_ap_CS_fsm_state31();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_CS_fsm_state7();
    void thread_ap_CS_fsm_state8();
    void thread_ap_CS_fsm_state9();
    void thread_ap_block_state3();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_rst_n_inv();
    void thread_data_hw_blk_n();
    void thread_data_hw_read();
    void thread_data_hw_tmp_address0();
    void thread_data_hw_tmp_ce0();
    void thread_data_hw_tmp_we0();
    void thread_dists_hw_blk_n();
    void thread_dists_hw_din();
    void thread_dists_hw_tmp_address0();
    void thread_dists_hw_tmp_ce0();
    void thread_dists_hw_tmp_we0();
    void thread_dists_hw_write();
    void thread_exitcond1_fu_364_p2();
    void thread_exitcond2_fu_333_p2();
    void thread_exitcond3_fu_305_p2();
    void thread_exitcond4_fu_288_p2();
    void thread_exitcond5_fu_262_p2();
    void thread_exitcond_fu_381_p2();
    void thread_grp_fu_235_opcode();
    void thread_grp_fu_235_p0();
    void thread_grp_fu_235_p1();
    void thread_i1_cast4_fu_300_p1();
    void thread_i2_cast3_fu_317_p1();
    void thread_i4_cast1_fu_376_p1();
    void thread_i_1_fu_311_p2();
    void thread_i_2_fu_268_p2();
    void thread_i_3_fu_387_p2();
    void thread_i_4_fu_339_p2();
    void thread_j3_cast2_cast_fu_350_p1();
    void thread_j3_cast2_fu_345_p1();
    void thread_j_1_fu_294_p2();
    void thread_j_2_fu_370_p2();
    void thread_j_cast5_cast_fu_274_p1();
    void thread_movie_tmp_address0();
    void thread_movie_tmp_ce0();
    void thread_movie_tmp_we0();
    void thread_tmp_11_cast_fu_329_p1();
    void thread_tmp_12_cast_fu_359_p1();
    void thread_tmp_3_fu_354_p2();
    void thread_tmp_4_fu_250_p3();
    void thread_tmp_5_cast_fu_258_p1();
    void thread_tmp_8_cast_fu_283_p1();
    void thread_tmp_8_fu_278_p2();
    void thread_tmp_s_fu_321_p3();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
